# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'genie_ui.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_NameChecker(object):
    def setupUi(self, NameChecker):
        NameChecker.setObjectName(_fromUtf8("NameChecker"))
        NameChecker.resize(1032, 684)
        font = QtGui.QFont()
        font.setPointSize(9)
        NameChecker.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("lamp.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        NameChecker.setWindowIcon(icon)
        NameChecker.setStyleSheet(_fromUtf8("QWidget{\n"
"background-color: rgb(225, 225, 225);\n"
"}\n"
"QCheckBox{\n"
"width:130%;\n"
"}\n"
"QCheckBox:hover{\n"
"color:rgb(100,100,100);\n"
"}\n"
"QTextEdit{\n"
"border: 2px solid rgb(238, 238, 238);\n"
"border-radius: 6px;\n"
"padding: 5px;\n"
"background-color: white;\n"
"}\n"
"QTextBrowser{\n"
"border: 2px solid rgb(238, 238, 238);\n"
"border-radius: 6px;\n"
"padding: 5px;\n"
"background-color: white;\n"
"}\n"
"QLineEdit{\n"
"border: 2px solid rgb(238, 238, 238);\n"
"border-radius: 6px;\n"
"background-color: white;\n"
"}\n"
"QLabel{\n"
"padding-top:5px;\n"
"color: black;\n"
"font: bold;\n"
"}\n"
"QPushButton {\n"
"color: black;\n"
"border: 2px solid rgb(204, 204, 204);\n"
"border-radius: 11px;\n"
"padding: 5px;\n"
"background: qradialgradient(cx: 0.2, cy: 1.3,\n"
"fx: 1.0, fy: 0.5,\n"
"radius: 1.35, stop: 0 rgb(228, 228, 228), stop: 1 rgb(208, 208, 208));\n"
"min-width: 80px;\n"
"font: bold;\n"
"}\n"
"QPushButton:pressed {\n"
"color:blue;\n"
"background: qradialgradient(cx: 0.4, cy: -0.1,\n"
"fx: 0.4, fy: -0.1,\n"
"radius: 1.35, stop: 0 #fff, stop: 1 rgb(245, 245, 245));\n"
"font:italic;\n"
"}\n"
"QPushButton:hover{\n"
"color:rgb(100,100,100);\n"
"}\n"
"QScrollBar::horizontal {\n"
"max-height: 7px;\n"
"}\n"
"QScrollBar::vertical {\n"
"max-width: 7px;\n"
"}\n"
"QScrollBar::handle:vertical {\n"
"background-color:rgb(200, 200, 200);\n"
"max-width: 4px;\n"
"}\n"
"QScrollBar::handle:horizontal {\n"
"background-color:rgb(200, 200, 200);\n"
"max-height: 4px;\n"
"}"))
        self.MainWindow = QtGui.QWidget(NameChecker)
        self.MainWindow.setStyleSheet(_fromUtf8("opacity: 0;"))
        self.MainWindow.setObjectName(_fromUtf8("MainWindow"))
        self.gridLayout_2 = QtGui.QGridLayout(self.MainWindow)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.MainTab = QtGui.QTabWidget(self.MainWindow)
        font = QtGui.QFont()
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setKerning(False)
        self.MainTab.setFont(font)
        self.MainTab.setMouseTracking(False)
        self.MainTab.setStyleSheet(_fromUtf8(""))
        self.MainTab.setTabPosition(QtGui.QTabWidget.North)
        self.MainTab.setObjectName(_fromUtf8("MainTab"))
        self.main_tab = QtGui.QWidget()
        self.main_tab.setStyleSheet(_fromUtf8(""))
        self.main_tab.setObjectName(_fromUtf8("main_tab"))
        self.gridLayout = QtGui.QGridLayout(self.main_tab)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setContentsMargins(-1, 0, -1, -1)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        self.verticalLayout_2.addItem(spacerItem)
        self.name_rationale_label_3 = QtGui.QLabel(self.main_tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.name_rationale_label_3.sizePolicy().hasHeightForWidth())
        self.name_rationale_label_3.setSizePolicy(sizePolicy)
        self.name_rationale_label_3.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.name_rationale_label_3.setFont(font)
        self.name_rationale_label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.name_rationale_label_3.setObjectName(_fromUtf8("name_rationale_label_3"))
        self.verticalLayout_2.addWidget(self.name_rationale_label_3, QtCore.Qt.AlignTop)
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.checkBox_all = QtGui.QCheckBox(self.main_tab)
        self.checkBox_all.setObjectName(_fromUtf8("checkBox_all"))
        self.horizontalLayout_13.addWidget(self.checkBox_all)
        self.verticalLayout_2.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.check_box_inn = QtGui.QCheckBox(self.main_tab)
        self.check_box_inn.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.check_box_inn.sizePolicy().hasHeightForWidth())
        self.check_box_inn.setSizePolicy(sizePolicy)
        self.check_box_inn.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.check_box_inn.setObjectName(_fromUtf8("check_box_inn"))
        self.checkboxGroup = QtGui.QButtonGroup(NameChecker)
        self.checkboxGroup.setObjectName(_fromUtf8("checkboxGroup"))
        self.checkboxGroup.setExclusive(False)
        self.checkboxGroup.addButton(self.check_box_inn)
        self.horizontalLayout_4.addWidget(self.check_box_inn)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.check_box_pharma = QtGui.QCheckBox(self.main_tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.check_box_pharma.sizePolicy().hasHeightForWidth())
        self.check_box_pharma.setSizePolicy(sizePolicy)
        self.check_box_pharma.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.check_box_pharma.setObjectName(_fromUtf8("check_box_pharma"))
        self.checkboxGroup.addButton(self.check_box_pharma)
        self.horizontalLayout_3.addWidget(self.check_box_pharma)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.check_box_project = QtGui.QCheckBox(self.main_tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.check_box_project.sizePolicy().hasHeightForWidth())
        self.check_box_project.setSizePolicy(sizePolicy)
        self.check_box_project.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.check_box_project.setStyleSheet(_fromUtf8(""))
        self.check_box_project.setObjectName(_fromUtf8("check_box_project"))
        self.checkboxGroup.addButton(self.check_box_project)
        self.horizontalLayout_2.addWidget(self.check_box_project)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.check_box_internal = QtGui.QCheckBox(self.main_tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.check_box_internal.sizePolicy().hasHeightForWidth())
        self.check_box_internal.setSizePolicy(sizePolicy)
        self.check_box_internal.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.check_box_internal.setStyleSheet(_fromUtf8(""))
        self.check_box_internal.setObjectName(_fromUtf8("check_box_internal"))
        self.checkboxGroup.addButton(self.check_box_internal)
        self.horizontalLayout_5.addWidget(self.check_box_internal)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.check_box_competitor = QtGui.QCheckBox(self.main_tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.check_box_competitor.sizePolicy().hasHeightForWidth())
        self.check_box_competitor.setSizePolicy(sizePolicy)
        self.check_box_competitor.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.check_box_competitor.setStyleSheet(_fromUtf8(""))
        self.check_box_competitor.setObjectName(_fromUtf8("check_box_competitor"))
        self.checkboxGroup.addButton(self.check_box_competitor)
        self.horizontalLayout_7.addWidget(self.check_box_competitor)
        self.verticalLayout_2.addLayout(self.horizontalLayout_7)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        self.verticalLayout_2.addItem(spacerItem1)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        self.verticalLayout_2.addItem(spacerItem2)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        self.verticalLayout_2.addItem(spacerItem3)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.exit_btn = QtGui.QPushButton(self.main_tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.exit_btn.sizePolicy().hasHeightForWidth())
        self.exit_btn.setSizePolicy(sizePolicy)
        self.exit_btn.setMaximumSize(QtCore.QSize(16777215, 28))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.exit_btn.setFont(font)
        self.exit_btn.setStyleSheet(_fromUtf8(":hover{\n"
"color:red;\n"
"}"))
        self.exit_btn.setObjectName(_fromUtf8("exit_btn"))
        self.horizontalLayout_10.addWidget(self.exit_btn)
        self.verticalLayout_2.addLayout(self.horizontalLayout_10)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.line_9 = QtGui.QFrame(self.main_tab)
        self.line_9.setFrameShape(QtGui.QFrame.VLine)
        self.line_9.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_9.setObjectName(_fromUtf8("line_9"))
        self.horizontalLayout.addWidget(self.line_9)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.name_rationale_label_2 = QtGui.QLabel(self.main_tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.name_rationale_label_2.sizePolicy().hasHeightForWidth())
        self.name_rationale_label_2.setSizePolicy(sizePolicy)
        self.name_rationale_label_2.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.name_rationale_label_2.setFont(font)
        self.name_rationale_label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.name_rationale_label_2.setObjectName(_fromUtf8("name_rationale_label_2"))
        self.verticalLayout_3.addWidget(self.name_rationale_label_2)
        self.textBrowser_stripped = QtGui.QTextBrowser(self.main_tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textBrowser_stripped.sizePolicy().hasHeightForWidth())
        self.textBrowser_stripped.setSizePolicy(sizePolicy)
        self.textBrowser_stripped.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.textBrowser_stripped.setFont(font)
        self.textBrowser_stripped.setStyleSheet(_fromUtf8("background-color: white;"))
        self.textBrowser_stripped.setObjectName(_fromUtf8("textBrowser_stripped"))
        self.verticalLayout_3.addWidget(self.textBrowser_stripped)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.line_4 = QtGui.QFrame(self.main_tab)
        self.line_4.setFrameShape(QtGui.QFrame.VLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.horizontalLayout.addWidget(self.line_4)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.name_rationale_label = QtGui.QLabel(self.main_tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.name_rationale_label.sizePolicy().hasHeightForWidth())
        self.name_rationale_label.setSizePolicy(sizePolicy)
        self.name_rationale_label.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.name_rationale_label.setFont(font)
        self.name_rationale_label.setAlignment(QtCore.Qt.AlignCenter)
        self.name_rationale_label.setObjectName(_fromUtf8("name_rationale_label"))
        self.verticalLayout.addWidget(self.name_rationale_label)
        self.textEdit_names = QtGui.QPlainTextEdit(self.main_tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEdit_names.sizePolicy().hasHeightForWidth())
        self.textEdit_names.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.textEdit_names.setFont(font)
        self.textEdit_names.setStyleSheet(_fromUtf8("background-color: white;"))
        self.textEdit_names.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.textEdit_names.setLineWrapMode(QtGui.QPlainTextEdit.NoWrap)
        self.textEdit_names.setObjectName(_fromUtf8("textEdit_names"))
        self.verticalLayout.addWidget(self.textEdit_names)
        self.save_names_btn = QtGui.QPushButton(self.main_tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.save_names_btn.sizePolicy().hasHeightForWidth())
        self.save_names_btn.setSizePolicy(sizePolicy)
        self.save_names_btn.setStyleSheet(_fromUtf8(""))
        self.save_names_btn.setObjectName(_fromUtf8("save_names_btn"))
        self.verticalLayout.addWidget(self.save_names_btn)
        self.sort_names_btn = QtGui.QPushButton(self.main_tab)
        self.sort_names_btn.setStyleSheet(_fromUtf8(""))
        self.sort_names_btn.setObjectName(_fromUtf8("sort_names_btn"))
        self.verticalLayout.addWidget(self.sort_names_btn)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.line_10 = QtGui.QFrame(self.main_tab)
        self.line_10.setFrameShape(QtGui.QFrame.VLine)
        self.line_10.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_10.setObjectName(_fromUtf8("line_10"))
        self.horizontalLayout.addWidget(self.line_10)
        self.verticalLayout_7 = QtGui.QVBoxLayout()
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.name_conflict_label = QtGui.QLabel(self.main_tab)
        self.name_conflict_label.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.name_conflict_label.sizePolicy().hasHeightForWidth())
        self.name_conflict_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.name_conflict_label.setFont(font)
        self.name_conflict_label.setAlignment(QtCore.Qt.AlignCenter)
        self.name_conflict_label.setObjectName(_fromUtf8("name_conflict_label"))
        self.verticalLayout_7.addWidget(self.name_conflict_label)
        self.textBrowser_conflicts = QtGui.QTextBrowser(self.main_tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textBrowser_conflicts.sizePolicy().hasHeightForWidth())
        self.textBrowser_conflicts.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.textBrowser_conflicts.setFont(font)
        self.textBrowser_conflicts.setStyleSheet(_fromUtf8("background-color: white;"))
        self.textBrowser_conflicts.setLineWrapMode(QtGui.QTextEdit.NoWrap)
        self.textBrowser_conflicts.setObjectName(_fromUtf8("textBrowser_conflicts"))
        self.verticalLayout_7.addWidget(self.textBrowser_conflicts)
        self.lineEdit_ignore = QtGui.QLineEdit(self.main_tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_ignore.sizePolicy().hasHeightForWidth())
        self.lineEdit_ignore.setSizePolicy(sizePolicy)
        self.lineEdit_ignore.setStyleSheet(_fromUtf8("border:none;"))
        self.lineEdit_ignore.setObjectName(_fromUtf8("lineEdit_ignore"))
        self.verticalLayout_7.addWidget(self.lineEdit_ignore)
        self.check_names_btn = QtGui.QPushButton(self.main_tab)
        self.check_names_btn.setStyleSheet(_fromUtf8(""))
        self.check_names_btn.setObjectName(_fromUtf8("check_names_btn"))
        self.verticalLayout_7.addWidget(self.check_names_btn)
        self.horizontalLayout.addLayout(self.verticalLayout_7)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.MainTab.addTab(self.main_tab, _fromUtf8(""))
        self.avoids_tab = QtGui.QWidget()
        self.avoids_tab.setObjectName(_fromUtf8("avoids_tab"))
        self.gridLayout_3 = QtGui.QGridLayout(self.avoids_tab)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.label_2 = QtGui.QLabel(self.avoids_tab)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout_5.addWidget(self.label_2)
        self.plainTextEdit_project = QtGui.QPlainTextEdit(self.avoids_tab)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.plainTextEdit_project.setFont(font)
        self.plainTextEdit_project.setStyleSheet(_fromUtf8("background-color: white;"))
        self.plainTextEdit_project.setObjectName(_fromUtf8("plainTextEdit_project"))
        self.verticalLayout_5.addWidget(self.plainTextEdit_project)
        self.horizontalLayout_8.addLayout(self.verticalLayout_5)
        self.line_7 = QtGui.QFrame(self.avoids_tab)
        self.line_7.setFrameShape(QtGui.QFrame.VLine)
        self.line_7.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_7.setObjectName(_fromUtf8("line_7"))
        self.horizontalLayout_8.addWidget(self.line_7)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.label = QtGui.QLabel(self.avoids_tab)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout_4.addWidget(self.label)
        self.plainTextEdit_internal = QtGui.QPlainTextEdit(self.avoids_tab)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.plainTextEdit_internal.setFont(font)
        self.plainTextEdit_internal.setStyleSheet(_fromUtf8("background-color: white;"))
        self.plainTextEdit_internal.setObjectName(_fromUtf8("plainTextEdit_internal"))
        self.verticalLayout_4.addWidget(self.plainTextEdit_internal)
        self.horizontalLayout_8.addLayout(self.verticalLayout_4)
        self.line_8 = QtGui.QFrame(self.avoids_tab)
        self.line_8.setFrameShape(QtGui.QFrame.VLine)
        self.line_8.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_8.setObjectName(_fromUtf8("line_8"))
        self.horizontalLayout_8.addWidget(self.line_8)
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.label_3 = QtGui.QLabel(self.avoids_tab)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.verticalLayout_6.addWidget(self.label_3)
        self.plainTextEdit_competitor = QtGui.QPlainTextEdit(self.avoids_tab)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.plainTextEdit_competitor.setFont(font)
        self.plainTextEdit_competitor.setStyleSheet(_fromUtf8("background-color: white;"))
        self.plainTextEdit_competitor.setObjectName(_fromUtf8("plainTextEdit_competitor"))
        self.verticalLayout_6.addWidget(self.plainTextEdit_competitor)
        self.horizontalLayout_8.addLayout(self.verticalLayout_6)
        self.gridLayout_3.addLayout(self.horizontalLayout_8, 0, 0, 1, 1)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem4)
        self.save_avoids_btn = QtGui.QPushButton(self.avoids_tab)
        self.save_avoids_btn.setObjectName(_fromUtf8("save_avoids_btn"))
        self.horizontalLayout_6.addWidget(self.save_avoids_btn)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem5)
        self.clear_avoids_btn = QtGui.QPushButton(self.avoids_tab)
        self.clear_avoids_btn.setObjectName(_fromUtf8("clear_avoids_btn"))
        self.horizontalLayout_6.addWidget(self.clear_avoids_btn)
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem6)
        self.gridLayout_3.addLayout(self.horizontalLayout_6, 1, 0, 1, 1)
        self.MainTab.addTab(self.avoids_tab, _fromUtf8(""))
        self.url_tab = QtGui.QWidget()
        self.url_tab.setObjectName(_fromUtf8("url_tab"))
        self.gridLayout_6 = QtGui.QGridLayout(self.url_tab)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.horizontalLayout_17 = QtGui.QHBoxLayout()
        self.horizontalLayout_17.setObjectName(_fromUtf8("horizontalLayout_17"))
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem7)
        self.verticalLayout_10 = QtGui.QVBoxLayout()
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        self.label_10 = QtGui.QLabel(self.url_tab)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.verticalLayout_10.addWidget(self.label_10)
        self.textBrowser_url_status = QtGui.QTextBrowser(self.url_tab)
        self.textBrowser_url_status.setStyleSheet(_fromUtf8("background-color: white;"))
        self.textBrowser_url_status.setLineWrapMode(QtGui.QTextEdit.NoWrap)
        self.textBrowser_url_status.setObjectName(_fromUtf8("textBrowser_url_status"))
        self.verticalLayout_10.addWidget(self.textBrowser_url_status)
        self.get_url_btn = QtGui.QPushButton(self.url_tab)
        self.get_url_btn.setObjectName(_fromUtf8("get_url_btn"))
        self.verticalLayout_10.addWidget(self.get_url_btn)
        self.horizontalLayout_17.addLayout(self.verticalLayout_10)
        spacerItem8 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem8)
        self.gridLayout_6.addLayout(self.horizontalLayout_17, 0, 0, 1, 1)
        self.MainTab.addTab(self.url_tab, _fromUtf8(""))
        self.pharma_tab = QtGui.QWidget()
        self.pharma_tab.setObjectName(_fromUtf8("pharma_tab"))
        self.gridLayout_5 = QtGui.QGridLayout(self.pharma_tab)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.verticalLayout_8 = QtGui.QVBoxLayout()
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.label_11 = QtGui.QLabel(self.pharma_tab)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.verticalLayout_8.addWidget(self.label_11)
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.label_5 = QtGui.QLabel(self.pharma_tab)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_11.addWidget(self.label_5)
        self.line_17 = QtGui.QFrame(self.pharma_tab)
        self.line_17.setFrameShape(QtGui.QFrame.VLine)
        self.line_17.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_17.setObjectName(_fromUtf8("line_17"))
        self.horizontalLayout_11.addWidget(self.line_17)
        self.textBrowser_pharma_prefix = QtGui.QTextBrowser(self.pharma_tab)
        self.textBrowser_pharma_prefix.setStyleSheet(_fromUtf8("background-color:rgb(255, 255, 255);font-size:10pt"))
        self.textBrowser_pharma_prefix.setLineWrapMode(QtGui.QTextEdit.NoWrap)
        self.textBrowser_pharma_prefix.setObjectName(_fromUtf8("textBrowser_pharma_prefix"))
        self.horizontalLayout_11.addWidget(self.textBrowser_pharma_prefix)
        spacerItem9 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.horizontalLayout_11.addItem(spacerItem9)
        self.verticalLayout_8.addLayout(self.horizontalLayout_11)
        self.line_3 = QtGui.QFrame(self.pharma_tab)
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.verticalLayout_8.addWidget(self.line_3)
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.label_6 = QtGui.QLabel(self.pharma_tab)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_12.addWidget(self.label_6)
        self.line_16 = QtGui.QFrame(self.pharma_tab)
        self.line_16.setFrameShape(QtGui.QFrame.VLine)
        self.line_16.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_16.setObjectName(_fromUtf8("line_16"))
        self.horizontalLayout_12.addWidget(self.line_16)
        self.textBrowser_pharma_infix = QtGui.QTextBrowser(self.pharma_tab)
        self.textBrowser_pharma_infix.setStyleSheet(_fromUtf8("background-color:rgb(255, 255, 255);font-size:10pt"))
        self.textBrowser_pharma_infix.setLineWrapMode(QtGui.QTextEdit.NoWrap)
        self.textBrowser_pharma_infix.setObjectName(_fromUtf8("textBrowser_pharma_infix"))
        self.horizontalLayout_12.addWidget(self.textBrowser_pharma_infix)
        spacerItem10 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.horizontalLayout_12.addItem(spacerItem10)
        self.verticalLayout_8.addLayout(self.horizontalLayout_12)
        self.line_2 = QtGui.QFrame(self.pharma_tab)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.verticalLayout_8.addWidget(self.line_2)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.label_4 = QtGui.QLabel(self.pharma_tab)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_9.addWidget(self.label_4)
        self.line_15 = QtGui.QFrame(self.pharma_tab)
        self.line_15.setFrameShape(QtGui.QFrame.VLine)
        self.line_15.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_15.setObjectName(_fromUtf8("line_15"))
        self.horizontalLayout_9.addWidget(self.line_15)
        self.textBrowser_pharma_suffix = QtGui.QTextBrowser(self.pharma_tab)
        self.textBrowser_pharma_suffix.setStyleSheet(_fromUtf8("background-color:rgb(255, 255, 255);font-size:10pt"))
        self.textBrowser_pharma_suffix.setLineWrapMode(QtGui.QTextEdit.NoWrap)
        self.textBrowser_pharma_suffix.setObjectName(_fromUtf8("textBrowser_pharma_suffix"))
        self.horizontalLayout_9.addWidget(self.textBrowser_pharma_suffix)
        spacerItem11 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.horizontalLayout_9.addItem(spacerItem11)
        self.verticalLayout_8.addLayout(self.horizontalLayout_9)
        self.gridLayout_5.addLayout(self.verticalLayout_8, 0, 0, 1, 1)
        self.MainTab.addTab(self.pharma_tab, _fromUtf8(""))
        self.inn_tab = QtGui.QWidget()
        self.inn_tab.setObjectName(_fromUtf8("inn_tab"))
        self.gridLayout_4 = QtGui.QGridLayout(self.inn_tab)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.verticalLayout_9 = QtGui.QVBoxLayout()
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.label_12 = QtGui.QLabel(self.inn_tab)
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.verticalLayout_9.addWidget(self.label_12)
        self.horizontalLayout_14 = QtGui.QHBoxLayout()
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        self.label_7 = QtGui.QLabel(self.inn_tab)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout_14.addWidget(self.label_7)
        self.line_14 = QtGui.QFrame(self.inn_tab)
        self.line_14.setFrameShape(QtGui.QFrame.VLine)
        self.line_14.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_14.setObjectName(_fromUtf8("line_14"))
        self.horizontalLayout_14.addWidget(self.line_14)
        self.textBrowser_inn_prefix = QtGui.QTextBrowser(self.inn_tab)
        self.textBrowser_inn_prefix.setStyleSheet(_fromUtf8("background-color: white;font-size:10pt"))
        self.textBrowser_inn_prefix.setLineWrapMode(QtGui.QTextEdit.NoWrap)
        self.textBrowser_inn_prefix.setObjectName(_fromUtf8("textBrowser_inn_prefix"))
        self.horizontalLayout_14.addWidget(self.textBrowser_inn_prefix)
        spacerItem12 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.horizontalLayout_14.addItem(spacerItem12)
        self.verticalLayout_9.addLayout(self.horizontalLayout_14)
        self.line_5 = QtGui.QFrame(self.inn_tab)
        self.line_5.setFrameShape(QtGui.QFrame.HLine)
        self.line_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_5.setObjectName(_fromUtf8("line_5"))
        self.verticalLayout_9.addWidget(self.line_5)
        self.horizontalLayout_15 = QtGui.QHBoxLayout()
        self.horizontalLayout_15.setObjectName(_fromUtf8("horizontalLayout_15"))
        self.label_8 = QtGui.QLabel(self.inn_tab)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.horizontalLayout_15.addWidget(self.label_8)
        self.line_13 = QtGui.QFrame(self.inn_tab)
        self.line_13.setFrameShape(QtGui.QFrame.VLine)
        self.line_13.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_13.setObjectName(_fromUtf8("line_13"))
        self.horizontalLayout_15.addWidget(self.line_13)
        self.textBrowser_inn_infix = QtGui.QTextBrowser(self.inn_tab)
        self.textBrowser_inn_infix.setStyleSheet(_fromUtf8("background-color:rgb(255, 255, 255);font-size:10pt"))
        self.textBrowser_inn_infix.setLineWrapMode(QtGui.QTextEdit.NoWrap)
        self.textBrowser_inn_infix.setObjectName(_fromUtf8("textBrowser_inn_infix"))
        self.horizontalLayout_15.addWidget(self.textBrowser_inn_infix)
        spacerItem13 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.horizontalLayout_15.addItem(spacerItem13)
        self.verticalLayout_9.addLayout(self.horizontalLayout_15)
        self.line_6 = QtGui.QFrame(self.inn_tab)
        self.line_6.setFrameShape(QtGui.QFrame.HLine)
        self.line_6.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_6.setObjectName(_fromUtf8("line_6"))
        self.verticalLayout_9.addWidget(self.line_6)
        self.horizontalLayout_16 = QtGui.QHBoxLayout()
        self.horizontalLayout_16.setObjectName(_fromUtf8("horizontalLayout_16"))
        self.label_9 = QtGui.QLabel(self.inn_tab)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.horizontalLayout_16.addWidget(self.label_9)
        self.line_11 = QtGui.QFrame(self.inn_tab)
        self.line_11.setFrameShape(QtGui.QFrame.VLine)
        self.line_11.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_11.setObjectName(_fromUtf8("line_11"))
        self.horizontalLayout_16.addWidget(self.line_11)
        self.textBrowser_inn_suffix = QtGui.QTextBrowser(self.inn_tab)
        self.textBrowser_inn_suffix.setStyleSheet(_fromUtf8("background-color:rgb(255, 255, 255);font-size:10pt"))
        self.textBrowser_inn_suffix.setLineWrapMode(QtGui.QTextEdit.NoWrap)
        self.textBrowser_inn_suffix.setObjectName(_fromUtf8("textBrowser_inn_suffix"))
        self.horizontalLayout_16.addWidget(self.textBrowser_inn_suffix)
        spacerItem14 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.horizontalLayout_16.addItem(spacerItem14)
        self.verticalLayout_9.addLayout(self.horizontalLayout_16)
        self.gridLayout_4.addLayout(self.verticalLayout_9, 2, 0, 1, 1)
        self.MainTab.addTab(self.inn_tab, _fromUtf8(""))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.gridLayout_7 = QtGui.QGridLayout(self.tab)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.horizontalLayout_18 = QtGui.QHBoxLayout()
        self.horizontalLayout_18.setObjectName(_fromUtf8("horizontalLayout_18"))
        self.verticalLayout_11 = QtGui.QVBoxLayout()
        self.verticalLayout_11.setObjectName(_fromUtf8("verticalLayout_11"))
        self.label_13 = QtGui.QLabel(self.tab)
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.verticalLayout_11.addWidget(self.label_13)
        self.names_text = QtGui.QTextEdit(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.names_text.sizePolicy().hasHeightForWidth())
        self.names_text.setSizePolicy(sizePolicy)
        self.names_text.setMaximumSize(QtCore.QSize(100, 16777215))
        self.names_text.setStyleSheet(_fromUtf8("background-color: white;font-size:10pt"))
        self.names_text.setObjectName(_fromUtf8("names_text"))
        self.verticalLayout_11.addWidget(self.names_text)
        self.PIU_radio = QtGui.QRadioButton(self.tab)
        self.PIU_radio.setObjectName(_fromUtf8("PIU_radio"))
        self.verticalLayout_11.addWidget(self.PIU_radio)
        self.structural_radio = QtGui.QRadioButton(self.tab)
        self.structural_radio.setObjectName(_fromUtf8("structural_radio"))
        self.verticalLayout_11.addWidget(self.structural_radio)
        self.horizontalLayout_18.addLayout(self.verticalLayout_11)
        self.verticalLayout_12 = QtGui.QVBoxLayout()
        self.verticalLayout_12.setObjectName(_fromUtf8("verticalLayout_12"))
        self.label_14 = QtGui.QLabel(self.tab)
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.verticalLayout_12.addWidget(self.label_14)
        self.parsed_text = QtGui.QTextBrowser(self.tab)
        self.parsed_text.setStyleSheet(_fromUtf8("background-color: white;font-size:10pt"))
        self.parsed_text.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.parsed_text.setLineWrapMode(QtGui.QTextEdit.NoWrap)
        self.parsed_text.setObjectName(_fromUtf8("parsed_text"))
        self.verticalLayout_12.addWidget(self.parsed_text)
        self.parse_btn = QtGui.QPushButton(self.tab)
        self.parse_btn.setStyleSheet(_fromUtf8("margin:3px;"))
        self.parse_btn.setObjectName(_fromUtf8("parse_btn"))
        self.verticalLayout_12.addWidget(self.parse_btn)
        self.horizontalLayout_18.addLayout(self.verticalLayout_12)
        self.gridLayout_7.addLayout(self.horizontalLayout_18, 0, 0, 1, 1)
        self.MainTab.addTab(self.tab, _fromUtf8(""))
        self.gridLayout_2.addWidget(self.MainTab, 0, 0, 1, 1)
        NameChecker.setCentralWidget(self.MainWindow)
        self.statusbar = QtGui.QStatusBar(NameChecker)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        NameChecker.setStatusBar(self.statusbar)
        self.actionExit = QtGui.QAction(NameChecker)
        self.actionExit.setShortcut(_fromUtf8(""))
        self.actionExit.setObjectName(_fromUtf8("actionExit"))
        self.actionView_pharma_avoids = QtGui.QAction(NameChecker)
        self.actionView_pharma_avoids.setObjectName(_fromUtf8("actionView_pharma_avoids"))
        self.actionView_inn_avoids = QtGui.QAction(NameChecker)
        self.actionView_inn_avoids.setObjectName(_fromUtf8("actionView_inn_avoids"))
        self.actionProject_avoids = QtGui.QAction(NameChecker)
        self.actionProject_avoids.setObjectName(_fromUtf8("actionProject_avoids"))
        self.actionInternal_names = QtGui.QAction(NameChecker)
        self.actionInternal_names.setObjectName(_fromUtf8("actionInternal_names"))
        self.actionPresented_names = QtGui.QAction(NameChecker)
        self.actionPresented_names.setObjectName(_fromUtf8("actionPresented_names"))
        self.actionCompetitor_names = QtGui.QAction(NameChecker)
        self.actionCompetitor_names.setObjectName(_fromUtf8("actionCompetitor_names"))
        self.actionOptions = QtGui.QAction(NameChecker)
        self.actionOptions.setObjectName(_fromUtf8("actionOptions"))
        self.actionTool_1 = QtGui.QAction(NameChecker)
        self.actionTool_1.setObjectName(_fromUtf8("actionTool_1"))
        self.actionTool_style = QtGui.QAction(NameChecker)
        self.actionTool_style.setObjectName(_fromUtf8("actionTool_style"))
        self.actionTool_3 = QtGui.QAction(NameChecker)
        self.actionTool_3.setObjectName(_fromUtf8("actionTool_3"))
        self.actionTool_4 = QtGui.QAction(NameChecker)
        self.actionTool_4.setObjectName(_fromUtf8("actionTool_4"))
        self.actionTool_5 = QtGui.QAction(NameChecker)
        self.actionTool_5.setObjectName(_fromUtf8("actionTool_5"))
        self.actionSave_names = QtGui.QAction(NameChecker)
        self.actionSave_names.setObjectName(_fromUtf8("actionSave_names"))
        self.actionSort_names = QtGui.QAction(NameChecker)
        self.actionSort_names.setObjectName(_fromUtf8("actionSort_names"))
        self.actionFind_conflicts = QtGui.QAction(NameChecker)
        self.actionFind_conflicts.setObjectName(_fromUtf8("actionFind_conflicts"))
        self.actionClear_avoids = QtGui.QAction(NameChecker)
        self.actionClear_avoids.setObjectName(_fromUtf8("actionClear_avoids"))
        self.actionView_stripped_names = QtGui.QAction(NameChecker)
        self.actionView_stripped_names.setObjectName(_fromUtf8("actionView_stripped_names"))
        self.actionINN_avoids_password_required = QtGui.QAction(NameChecker)
        self.actionINN_avoids_password_required.setObjectName(_fromUtf8("actionINN_avoids_password_required"))
        self.actionPharma_Avoids_password_req = QtGui.QAction(NameChecker)
        self.actionPharma_Avoids_password_req.setObjectName(_fromUtf8("actionPharma_Avoids_password_req"))
        self.actionINN_avoids = QtGui.QAction(NameChecker)
        self.actionINN_avoids.setObjectName(_fromUtf8("actionINN_avoids"))
        self.actionPharma_avoids = QtGui.QAction(NameChecker)
        self.actionPharma_avoids.setObjectName(_fromUtf8("actionPharma_avoids"))
        self.actionAdd_avoids = QtGui.QAction(NameChecker)
        self.actionAdd_avoids.setObjectName(_fromUtf8("actionAdd_avoids"))

        self.retranslateUi(NameChecker)
        self.MainTab.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(NameChecker)

    def retranslateUi(self, NameChecker):
        NameChecker.setWindowTitle(_translate("NameChecker", "The Cristini Genie", None))
        self.name_rationale_label_3.setStatusTip(_translate("NameChecker", "Choose what you would like to screen against", None))
        self.name_rationale_label_3.setText(_translate("NameChecker", "Screen against:", None))
        self.checkBox_all.setStatusTip(_translate("NameChecker", "Check or uncheck all options", None))
        self.checkBox_all.setText(_translate("NameChecker", "Check / Uncheck All", None))
        self.check_box_inn.setStatusTip(_translate("NameChecker", "Check against INN avoids", None))
        self.check_box_inn.setText(_translate("NameChecker", "INN Avoids", None))
        self.check_box_pharma.setToolTip(_translate("NameChecker", "Check against Pharma avoids", None))
        self.check_box_pharma.setStatusTip(_translate("NameChecker", "Check against Pharma avoids", None))
        self.check_box_pharma.setText(_translate("NameChecker", "Pharma Avoids", None))
        self.check_box_project.setStatusTip(_translate("NameChecker", "Check against Project avoids", None))
        self.check_box_project.setText(_translate("NameChecker", "Project Avoids", None))
        self.check_box_internal.setStatusTip(_translate("NameChecker", "Check against Internal / Presented names", None))
        self.check_box_internal.setText(_translate("NameChecker", "Internal / Presented", None))
        self.check_box_competitor.setStatusTip(_translate("NameChecker", "Check against Competitor names", None))
        self.check_box_competitor.setText(_translate("NameChecker", "Competitors", None))
        self.exit_btn.setStatusTip(_translate("NameChecker", "Exit Name Checker [Ctrl+Q]", None))
        self.exit_btn.setText(_translate("NameChecker", "      Exit      ", None))
        self.name_rationale_label_2.setText(_translate("NameChecker", " Names", None))
        self.textBrowser_stripped.setStatusTip(_translate("NameChecker", "Shows names stripped of rationale/notes", None))
        self.name_rationale_label.setText(_translate("NameChecker", "Enter your names below", None))
        self.textEdit_names.setStatusTip(_translate("NameChecker", "Enter your names here", None))
        self.save_names_btn.setStatusTip(_translate("NameChecker", "Save your names to be checked [Ctrl+S]", None))
        self.save_names_btn.setText(_translate("NameChecker", "Commit Names", None))
        self.sort_names_btn.setStatusTip(_translate("NameChecker", "Sort created names alphabetically", None))
        self.sort_names_btn.setText(_translate("NameChecker", "Sort Names (A-Z)", None))
        self.name_conflict_label.setText(_translate("NameChecker", "Conflicts", None))
        self.textBrowser_conflicts.setStatusTip(_translate("NameChecker", "Displays names that contain conflicts", None))
        self.textBrowser_conflicts.setHtml(_translate("NameChecker", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'.Helvetica Neue DeskInterface\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:13pt;\"><br /></p></body></html>", None))
        self.lineEdit_ignore.setStatusTip(_translate("NameChecker", "Enter a stem to be ignored", None))
        self.lineEdit_ignore.setPlaceholderText(_translate("NameChecker", "Enter an INN stem to ignore here...", None))
        self.check_names_btn.setStatusTip(_translate("NameChecker", "Find conflicts with your names [Ctr+Enter]", None))
        self.check_names_btn.setText(_translate("NameChecker", "Find Conflicts", None))
        self.MainTab.setTabText(self.MainTab.indexOf(self.main_tab), _translate("NameChecker", "Main", None))
        self.label_2.setText(_translate("NameChecker", "Project Avoids", None))
        self.plainTextEdit_project.setStatusTip(_translate("NameChecker", "Add project specific avoids", None))
        self.label.setText(_translate("NameChecker", "Internal / Presented Names", None))
        self.plainTextEdit_internal.setStatusTip(_translate("NameChecker", "Add internal and/or presented names", None))
        self.label_3.setText(_translate("NameChecker", "Competitor Names", None))
        self.plainTextEdit_competitor.setStatusTip(_translate("NameChecker", "Add competitor names", None))
        self.save_avoids_btn.setText(_translate("NameChecker", "Save All", None))
        self.clear_avoids_btn.setText(_translate("NameChecker", "Clear All", None))
        self.MainTab.setTabText(self.MainTab.indexOf(self.avoids_tab), _translate("NameChecker", "Add Avoids", None))
        self.label_10.setText(_translate("NameChecker", "URL Availability", None))
        self.textBrowser_url_status.setStatusTip(_translate("NameChecker", "See URL availability", None))
        self.get_url_btn.setStatusTip(_translate("NameChecker", "Get URL Status", None))
        self.get_url_btn.setText(_translate("NameChecker", "Get URL Status!\n"
"(This may take a moment)", None))
        self.MainTab.setTabText(self.MainTab.indexOf(self.url_tab), _translate("NameChecker", "Get URL Status", None))
        self.label_11.setText(_translate("NameChecker", "Pharma Avoids", None))
        self.label_5.setText(_translate("NameChecker", "Pharma\n"
"Prefix", None))
        self.textBrowser_pharma_prefix.setStatusTip(_translate("NameChecker", "View pharma prefix avoids", None))
        self.label_6.setText(_translate("NameChecker", "Pharma\n"
"Infix  ", None))
        self.textBrowser_pharma_infix.setStatusTip(_translate("NameChecker", "View pharma infix avoids", None))
        self.label_4.setText(_translate("NameChecker", "Pharma\n"
"Suffix", None))
        self.textBrowser_pharma_suffix.setStatusTip(_translate("NameChecker", "View pharma suffix avoids", None))
        self.MainTab.setTabText(self.MainTab.indexOf(self.pharma_tab), _translate("NameChecker", "View Pharma Avoids", None))
        self.label_12.setText(_translate("NameChecker", "INN Stems", None))
        self.label_7.setText(_translate("NameChecker", " INN\n"
"  Prefix ", None))
        self.textBrowser_inn_prefix.setStatusTip(_translate("NameChecker", "View INN prefixes", None))
        self.label_8.setText(_translate("NameChecker", " INN\n"
"   Infix  ", None))
        self.textBrowser_inn_infix.setStatusTip(_translate("NameChecker", "View INN infixes", None))
        self.label_9.setText(_translate("NameChecker", " INN\n"
"  Suffix ", None))
        self.textBrowser_inn_suffix.setStatusTip(_translate("NameChecker", "View INN suffixes", None))
        self.MainTab.setTabText(self.MainTab.indexOf(self.inn_tab), _translate("NameChecker", "View INN Stems", None))
        self.label_13.setText(_translate("NameChecker", "Names", None))
        self.PIU_radio.setText(_translate("NameChecker", "PIU Keys", None))
        self.structural_radio.setText(_translate("NameChecker", "Structural Keys", None))
        self.label_14.setText(_translate("NameChecker", "Search Keys", None))
        self.parse_btn.setText(_translate("NameChecker", "Get search keys! [Ctrl+Enter]", None))
        self.parse_btn.setShortcut(_translate("NameChecker", "Ctrl+Return", None))
        self.MainTab.setTabText(self.MainTab.indexOf(self.tab), _translate("NameChecker", "Search Pal", None))
        self.actionExit.setText(_translate("NameChecker", "Leave", None))
        self.actionView_pharma_avoids.setText(_translate("NameChecker", "View Pharma Avoids", None))
        self.actionView_pharma_avoids.setStatusTip(_translate("NameChecker", "View Pharma Avoids", None))
        self.actionView_inn_avoids.setText(_translate("NameChecker", "View INN Avoids", None))
        self.actionProject_avoids.setText(_translate("NameChecker", "Project Avoids", None))
        self.actionInternal_names.setText(_translate("NameChecker", "Internal Names", None))
        self.actionPresented_names.setText(_translate("NameChecker", "Presented Names", None))
        self.actionCompetitor_names.setText(_translate("NameChecker", "Competitor Names", None))
        self.actionOptions.setText(_translate("NameChecker", "Options", None))
        self.actionOptions.setStatusTip(_translate("NameChecker", "View Options", None))
        self.actionTool_1.setText(_translate("NameChecker", "Tool 1", None))
        self.actionTool_style.setText(_translate("NameChecker", "Tool 2", None))
        self.actionTool_3.setText(_translate("NameChecker", "Tool 3", None))
        self.actionTool_4.setText(_translate("NameChecker", "Tool 4", None))
        self.actionTool_5.setText(_translate("NameChecker", "Tool 5", None))
        self.actionSave_names.setText(_translate("NameChecker", "Commit Names", None))
        self.actionSort_names.setText(_translate("NameChecker", "Sort Names (A-Z)", None))
        self.actionFind_conflicts.setText(_translate("NameChecker", "Find Conflicts", None))
        self.actionClear_avoids.setText(_translate("NameChecker", "Clear All Avoids", None))
        self.actionView_stripped_names.setText(_translate("NameChecker", "View names without rationale", None))
        self.actionINN_avoids_password_required.setText(_translate("NameChecker", "INN avoids (password req.)", None))
        self.actionPharma_Avoids_password_req.setText(_translate("NameChecker", "Pharma Avoids (password req.)", None))
        self.actionINN_avoids.setText(_translate("NameChecker", "INN Avoids", None))
        self.actionPharma_avoids.setText(_translate("NameChecker", "Pharma Avoids", None))
        self.actionAdd_avoids.setText(_translate("NameChecker", "Add Avoids", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    NameChecker = QtGui.QMainWindow()
    ui = Ui_NameChecker()
    ui.setupUi(NameChecker)
    NameChecker.show()
    sys.exit(app.exec_())
