PHARMA_AVOIDS_DICTIONARY = {}
PHARMA_AVOIDS_DICTIONARY["all_avoids"] = {
'-sef-' : 'Avoid unless product is a cephalosporin',
'privy-' : 'Negative connotations',
'-farc-' : 'Suggests "infarction"',
'-pox ' : 'Negative medical term',
'-pox-' : 'Negative medical term',
'sef-' : 'Avoid unless product is a cephalosporin',
'-privy-' : 'Negative connotations',
'-vix-' : 'Negative connotations',
'yaz-' : 'Too similar to Yaz',
'-io-' : 'Generic stem',
'-spic-' : 'Negative connotations',
'-sef' : 'Avoid unless product is a cephalosporin',
'-merd-' : 'Negative connotations in French and Italian',
'fizz-' : 'Negative connotations',
'-im' : 'Avoid if product is an intramuscular',
'pox-' : 'Negative medical term',
'-vin-' : 'Generic Stem',
'-ib' : 'Generic stem',
'-fizz-' : 'Negative connotations',
'-frez' : 'Can suggest "freezing"',
'-iv' : 'Identifying mode of administration',
'-averx-' : '"Adverse" as in side effects',
'cor-' : 'Avoid unless for cardio',
'spic-' : 'Negative connotations',
'bol-' : 'Generic Stem',
'yond-' : 'Too similar to Yondelis',
'bid-' : 'suggests "twice daily" dosing',
'-fizz' : 'Negative connotations',
'-vin' : 'Generic Stem',
'-averx' : '"Adverse" as in side effects',
'-tox-' : 'Negative connotations',
'-bol-' : 'Generic Stem',
'-bid' : 'suggests "twice daily" dosing',
'nig-' : 'Negative connotations',
'vin-' : 'Generic Stem',
'dol-' : 'Suggests "pain" in several romance languages',
'voza-' : 'Negative connotations',
'-help-' : '--',
'-vix' : 'Negative connotations',
'-vir' : 'Generic Stem',
'fo-' : '--',
'-cef-' : 'Avoid unless product is a cephalosporin',
'-aj-' : 'Generic stem',
'io-' : 'Generic stem',
'war-' : '--',
'-sal-' : 'Generic stem',
'-merd' : 'Negative connotations in French and Italian',
'-voza' : 'Negative connotations',
'-dol-' : 'Suggests "pain" in several romance languages',
'cox-' : '--',
'-spic' : 'Negative connotations',
'-bol' : 'Generic Stem',
'iv-' : 'Identifying mode of administration',
'-cef' : 'Avoid unless product is a cephalosporin',
'-dol' : 'Suggests "pain" in several romance languages',
'-infuse-' : '"Infusion" has a specific meaning in pharma',
'-frez-' : 'Can suggest "freezing"',
'pax-' : 'Too similar to Paxil',
'-help' : '--',
'im-' : 'Avoid if product is an intramuscular',
'-fo-' : '--',
'averx-' : '"Adverse" as in side effects',
'help-' : '--',
'-ium' : 'Generic stem',
'-tox' : 'Negative connotations',
'-sal' : 'Generic stem',
'merd-' : 'Negative connotations in French and Italian',
'-privy' : 'Negative connotations',
'cef-' : 'Avoid unless product is a cephalosporin',
'-infuse' : '"Infusion" has a specific meaning in pharma',
'-farc' : 'Suggests "infarction"',
'-cox-' : '--',
'tox-' : 'Negative connotations',
'infuse-' : '"Infusion" has a specific meaning in pharma',
'-ac' : '--',
'-ab' : 'Generic stem',
'frez-' : 'Can suggest "freezing"',
'vix-' : 'Negative connotations',
'sal-' : 'Generic stem',
'-yaz' : 'Too similar to Yaz',
'-cox' : '--',
'tid-' : 'Suggests "thrice daily" dosing',
'-vir-' : 'Generic Stem',
'-cor' : 'Avoid unless for cardio',
'-luxo' : 'Negative connotations',
'-voza-' : 'Negative connotations',
'jod-' : 'Carries negative connotations in Spanish',
'vir-' : 'Generic Stem',
'-nig ' : 'Negative connotations',
'-nig- ' : 'Negative connotations',
'-cor-' : 'Avoid unless for cardio',
'-yaz-' : 'Too similar to Yaz',
'farc-' : 'Suggests "infarction"',
'-tid' : 'Suggests "thrice daily" dosing',
'jaz-' : 'Too similar to Jazz Pharma',
}
PHARMA_AVOIDS_DICTIONARY["prefix"] = ["privy", "sef", "yaz", "fizz", "pox", "help", \
"cor", "cox", "bol", "yond", "bid", "nig", "vin", "dol", "voza", "fo", "io", "war", \
"fo", "spic", "iv", "pax", "im", "averx", "merd", "cef", "tox", "infuse", "frez", \
"vix", "sal", "tid", "jod", "vir", "farc", "jaz"]

PHARMA_AVOIDS_DICTIONARY["infix"] = ["sef", "farc", "pox", "privy", "vix", "io", "spic", \
"merd", "vin", "averx", "tox", "bol", "help", "cef", "aj", "dol", "infuse", "frez", "fo", \
"fizz", "cox", "vir", "voza", "sal", "cor", "yaz"]

PHARMA_AVOIDS_DICTIONARY["suffix"] = ["pox ", "sef", "ib", "im", "privy", "frez", "iv", \
"fizz", "vin", "nig- ", "averx", "bid", "vix", "vir", "merd", "voza", "spic", "bol", "cef", \
"dol", "help", "ium", "tox", "sal", "infuse", "farc", "ac", "ab", "yaz", "cox", "cor", "luxo", \
"nig ", "tid"]



INN_AVOIDS_DICTIONARY = {}
INN_AVOIDS_DICTIONARY["all_avoids"] = {
'-pladib' : 'phospholipase A2 inhibitors',
'-degib' : 'hedgehog signaling inhibitors',
'-estrant' : 'estrogen antagonists',
'imex-' : '(see -imex)',
'-anib' : 'angiogenesis inhibitors',
'-tril' : 'endopeptidase inhibitors',
'-taxel' : 'antineoplastics, taxane derivatives',
'calci-' : 'vitamin D analogues',
'-dronate' : 'calcium metabolism regulators',
'-ganan' : 'antimicrobial, bactericidal permeability increasing polypeptide',
'-terol' : 'bronchodilators (phenethylamine derivatives)',
'di-' : 'Verbal Not to Use',
'perflu-' : 'blood substitutes and/or diagnostics (perfluorochemicals)',
'-uplase' : 'urokinase-type plasminogen activators',
'-luren' : 'inducers of ribosomal readthrough of nonsense mutation mRNA stop codons',
'-virine' : 'non-nucleoside reverse transcriptase inhibitors, not benzoxazinone derivatives',
'-tiline' : 'antidepressants, dibenzo [a,d] cycloheptane or cyclopheptene derivatives',
'-fo(s)-' : 'antihyperlipidemics (clofibrate type)',
'-caine' : 'local anesthetics',
'-drine' : 'sympathomimetics',
'-bendazole' : 'anthelmintics (tibendazole type)',
'-telstat' : 'telomerase inhibitors',
'-navir' : '(see vir-)',
'rac-' : 'Verbal Not to Use',
'-giline' : 'MAO inhibitors, type B',
'-tercept' : 'transforming growth factor',
'-rozole' : 'aromatase inhibitors (imidazole/triazole derivatives)',
'-tizide' : 'diuretics, chlorothiazide derivatives',
'-zumab' : '(see -mab)',
'-gatran' : 'thrombin inhibitors (argatroban type)',
'-rian' : 'ryanodine receptor modulators',
'-pris-' : 'steroidal compounds acting on progesterone receptors',
'-flapon' : '5-lipoxygenase-activating protein (FLAP) inhibitors',
'-kin-' : 'interleukins as target',
'-proget' : 'nonsteroidal ligand for the progesterone receptor',
'-cisteine' : 'mucolytics, other than bromhexine derivatives',
'-fulven' : 'antineoplastic, acylfulven derivatives',
'-rinone' : 'cardiotonics (amrinone type)',
'-distim' : 'conjugates of two different types of colony-stimulating factors',
'-arotene' : 'arotinoid derivatives',
'-lintide' : 'amylin derivatives or mimics',
'-cain-' : 'class I antiarrhythmics, procainamide and lidocaine derivatives',
'-rolimus' : 'immunosuppressant, rapamycin derivatives',
'deci-' : 'Verbal Not to Use',
'-nicate' : 'antihypercholesterolaemic and/or vasodilating nicotinic acid esters',
'-racetam' : 'nootropes (piracetam type)',
'-ampanel' : 'antagonists',
'erg-' : '(see -erg-)',
'-cillinam' : 'antibiotics, 6-aminopenicillanic acid derivatives',
'-pab' : 'antibody mixtures/polyclonal antibodies, used instead of -mab',
'-iv' : 'Not necessarily prohibitive, but definitely causes hesitation',
'-paxar' : 'PAR1 antagonists',
'-milast' : 'type IV phosphodiesterase inhibitors',
'me-' : 'Verbal Not to Use',
'-tegr-' : 'integrin antagonists',
'-gab-' : 'gabamimetics',
'-mulin' : 'antibacterials, pleuromulin derivatives',
'-nal-' : 'narcotic agonists/antagonists (normorphine type)',
'-kin' : 'interleukins',
'-texafin' : 'texaphryn derivatives',
'-mj-' : 'Verbal Not to Use',
'-retin' : 'NO DEFINITION',
'-cizumab' : '(see -mab)',
'-lind' : 'pro-apoptotic cGMP phosphodiesterase inhibitors',
'-toxa-' : 'toxins',
'-golide' : 'dopamine receptor agonists, ergoline derivatives',
'-tecarin' : 'antineoplastics (rebeccamycin derivatives)',
'-pramine' : 'antidepressants (imipramine type)',
'-metacin' : 'anti-inflammatory agents (indomethacin type)',
'-ifen' : 'NO DEFINITION',
'-nidap' : 'nonsteroidal anti-inflammatory agents (tenidap type)',
'-fradil' : 'calcium channel blockers acting as vasodilators',
'-cridar' : '(see -dar)',
'-uclin' : 'mucosal tolerance inhibitors',
'-ditraz' : 'acaricide/tick repellent',
'-bersat' : 'anticonvulsants; antimigraine (benzoylamino-benzpyran derivatives)',
'z-' : 'Verbal Not to Use',
'-corat' : 'glucocorticoid receptor agonists ( not glucocorticoids)',
'-iphene' : '(see -ifene)',
'-begron' : 'beta 3 adrenoreceptor agonist',
'-denant' : 'adenosine 2A antagonists',
'-troban' : 'antithrombotics (thromboxane A2 receptor antagonists)',
'-ms-' : 'Verbal Not to Use',
'-parcil' : 'antithrombotics',
'-viroc' : 'CCR5 antagonists',
'-acid-' : 'derivatives)',
'-afil' : 'PDE5 inhibitors',
'-pirox' : 'antimycotics (pyridone derivatives)',
'-glutide' : 'GLP peptide analogs',
'-ciguat' : 'guanaline cyclase activator',
'-nidazole' : 'antiprotozoal substances (metronidazole type)',
'-tilide' : 'class III antiarrhythmics, sematilide derivatives',
'-mer' : 'polymers',
'-terone' : 'antiandrogens',
'-kiren' : 'renin inhibitors',
'-anserin' : 'serotonin 5-HT2 receptor antagonists',
'efex-' : 'Verbal Not to Use',
'pred-' : 'prednisone and prednisolone derivatives',
'cel-' : 'Verbal Not to Use',
'-leukin' : '(see -kin)',
'-lutamide' : 'non-steroid antiandrogens',
'-gliatin' : 'glucokinase enzyme inhibitors (typically antidiabetics)',
'-dotin' : 'synthetic analogs of the dolastatin series',
'-citinib' : '(see -tinib)',
'-lisib' : 'phosphatidylinositol 3-kinase (PI3K) inhibitors',
'-termin' : '(see -ermin)',
'-dore' : 'dopamine D2D3 receptor modulators',
'-ster-' : 'steroids (androgens, anabolics)',
'-rsen' : 'antisense oligonucleotides',
'-prim' : 'antibacterials (trimethoprim type)',
'-pamide' : 'diuretics (sulfamoylbenzoic acid derivatives)',
'-pril' : 'antihypertensives (ACE inhibitors)',
'-ner-' : 'neurologic indications (replaces -neu-)',
'-prost-' : 'prostaglandins',
'-fiba-' : 'platelet aggregation inhibitor (GPIIb/IIIa receptor',
'-moren' : 'non-peptidic growth hormone secretagogues',
'-xizu-' : 'combination of humanized and chimeric chains',
'-dismase' : 'superoxide dismutase activity',
'-sonan' : '5-HT1B receptor antagonists',
'-tegrast' : 'see ast',
'-pafant' : 'platelet-activating factor antagonists',
'-ixafor' : 'CXCR4 antagonists',
'-vaptan' : 'vasopressin receptor antagonists',
'-oxopine' : 'tricyclic compounds',
'ca-' : 'Verbal Not to Use',
'-nercept' : '(see -cept)',
'-mx-' : 'Verbal Not to Use',
'-bercept' : 'Review -cept',
'-casan' : 'caspase (interleukin 1b) converting enzyme inhibitors',
'-naritide' : 'peptides and glycopeptides',
'-pred' : 'prednisone and prednisolone derivatives',
'-azam' : 'diazepam derivatives',
'-bulin' : 'antineoplastics (mitotic inhibitors; tubulin binders)',
'-xaban' : 'antithrombotic: blood coagulation factor XA inhibitors',
'-denoson' : 'adenosine A receptor agonists',
'-thiazide' : 'diuretics (thiazide derivatives)',
'-ph-' : 'Verbal Not to Use',
'-planin' : 'antibacterials (Actinoplanes strains)',
'cort-' : 'corticosteroids, except prednisolone derivatives',
'-paratide' : '(see -tide)',
'-fiban' : 'receptor antagonists (glycoprotein IIb/IIIa receptor antagonists)',
'-trakinra' : 'interleukin receptor antagonists',
'-fexorate' : 'farnesoid X receptor agonists',
'-brate' : 'clofibrate derivatives',
'-mapimod' : 'mitogen-activated protein (MAP) kinase inhibitors',
'-zotide' : 'zonulin antagonists',
'-pitant' : '(see -tant)',
'-nab' : '(see -nab-)',
'-cycline' : 'antibiotics (tetracycline derivatives)',
'io-' : 'iodine-containing contrast media',
'-bactam' : 'beta-lactamase inhibitors',
'-moxin' : 'monoamine oxidase inhibitors (hydrazine derivatives)',
'-sulfan' : 'antineoplastics, alkylating agents (methanesulfonate derivatives)',
'-quine' : 'quinoline derivatives',
'-fenamic' : 'anti-inflammatory agents (anthranilic acid',
'-trodast' : 'thromboxane A2 receptor antagonists',
'-cort' : 'corticosteroids, except prednisolone derivatives',
'-folastat' : '(see -stat)',
'-azenil' : 'benzodiazepine receptor agonists/antagonists',
'-lutril' : 'neutral endopeptidase inhibitors possessing additional endothelin converting enzyme inhibitory activity',
'al-' : 'Verbal Not to Use',
'lev-' : 'Verbal Not to Use',
'-dyl' : 'vasodilators',
'-calcet' : 'calcium receptor agonists',
'-tinib' : 'tyrosine kinase inhibitors',
'-serpine' : 'Rauwolfia alkaloid derivatives',
'-ectin' : 'antiparasitics (ivermectin type)',
'-restat-' : 'aldose-reductase inhibitors',
'-flurane' : 'general inhalation anesthetics (halogenated alkane derivatives)',
'-icam' : 'anti-inflammatory agents (isoxicam type)',
'-virimat' : 'antiviral, disrupts viral maturation',
'-cog' : 'blood coagulation factors',
'-izine' : 'diphenylmethyl piperazine derivatives',
'barb-' : 'barbituric acid derivatives',
'-kalant' : 'potassium channel antagonists',
'-azepam' : 'antianxiety agents (diazepam type)',
'-otermin' : 'bone morphogenetic proteins',
'-farcept' : 'interferon receptors',
'-camsule' : 'camphorsulfonic acid derivatives used as UVA sunscreens',
'-ifene' : 'antiestrogens of the clomifene and tamoxifen groups',
'-azoline' : 'antihistamines/local vasoconstrictors (antazoline type)',
'-clomol' : 'heat-shock protein inducers, bimoclomal type',
'-trilat' : 'NO DEFINITION',
'-triptan' : 'antimigraine agents (5-HT1 receptor agonists); sumatriptan derivatives',
'-drimer' : '(see -mer)',
'-napant' : 'inhibitor of apoptosis protein (IAP) inhibitors',
'-kacin' : 'antibiotics obtained from Streptomyces kanamyceticus (related to kanamycin)',
'-prilat' : 'antihypertensives (ACE inhibitors) (diacid analogs of the -pril entity)',
'-nesib' : 'kinesin inhibitors',
'-ciclib' : 'cyclin dependent kinase inhibitors (formerly -cidib)',
'fo-' : 'Verbal Not to Use',
'-tegravir' : 'integrase inhibitors',
'-stim' : 'colony-stimulating factors',
'ben-' : 'Verbal Not to Use',
'-co-' : 'complement receptors',
'-mf-' : 'Verbal Not to Use',
'-imidar' : 'see dar',
'-afenone' : 'antiarrhythmics (propafenone derivatives)',
'nitro-' : 'NO2 - derivatives',
'-vircept' : '(see -cept)',
'-trakin' : 'interleukin-4 analogues and derivatives',
'-punil' : 'mitochondrial benzodiazepine receptor (MBR) selective, partial, or inverse agonists (purine derivatives)',
'-imus' : 'immunosuppressives',
'-farin' : 'warfarin analogs',
'-carnil' : 'benzodiazepine receptor antagonists/agonists (carboline derivatives)',
'-mab' : 'monoclonal antibodies',
'-tansine' : 'maytansinoid derivatives',
'-oxetine' : 'antidepressants (fluoxetine type)',
'-golix' : 'GnRH receptor antagonists (nonpeptide)',
'peg-' : 'PEGylated compounds',
'-ox' : 'antacids, aluminium derivatives',
'-apsel' : 'P-selectin antagonists',
'-butan' : 'antiseptics (dapabutan type)',
'-tiostat' : 'glutathione -s- transferase inhibitors',
'-oxacin' : 'antibacterials (quinolone derivatives)',
'-gosivir' : '(see -vir)',
'-ol' : 'for alcohols and phenols',
'-tecan' : 'antineoplastics (camptothecine derivatives)',
'-vudine' : 'antineoplastics; antivirals (zidovudine group) (exception: edoxudine)',
'-semide' : 'diuretics (furosemide type)',
'-steine' : 'mucolytics, other than bromhexine derivatives',
'-dapsone' : 'antimycobacterials (diaminodiphenylsulfone derivatives)',
'-gab' : '(see -gab-)',
'-olone' : 'steroids (not prednisolone derivatives)',
'-inostat' : 'inhibitors of histone deacetylase',
'-murtide' : 'peptides with muranic acid present',
'-rs-' : 'Verbal Not to Use',
'-ne-' : 'neurologic indications (replaces -neu-)',
'-ibine' : 'ribofuranyl-derivatives of the "pyrazofurin" type',
'trop-' : 'atropine derivatives',
'-mt-' : 'Verbal Not to Use',
'-ibat' : 'ileal bile acid transport inhibitor',
'-elvakin' : '(see -kin)',
'-fenin' : 'diagnostic aids ((phenylcarbamoyl)methyl iminodiacetic acid derivatives)',
'str-' : 'Verbal Not to Use',
'-prinim' : 'nootropic agents, purine derivatives',
'-onide' : 'topical steroids (acetal derivatives)',
'-ine' : 'alkaloids and organic bases',
'gli-' : 'antihyperglycemics',
'-caleret' : 'calcium receptor antagonists',
'-h-' : 'Verbal Not to Use',
'-setrag' : 'serotonin 5-HT receptor agonists, not principally 5-HT2',
'-azosin' : 'antihypertensives (prazosin type)',
'-gest-' : 'progestins',
'-prazole' : 'antiulcer agents (benzimidazole derivatives)',
'-rafenib' : 'raf kinase (serine/threonine kinase) inhibitors',
'-vin-' : 'NO DEFINITION',
'-citabine' : 'nucleoside antiviral or antineoplastic agents, cytarabine or azarabine derivatives',
'-triptyline' : 'antidepressants (dibenzo[a,d]cycloheptane derivatives)',
'-zepine' : '(see -pine)',
'-mantine' : '(adamantane derivatives)',
'-rizine' : '(see -izine)',
'-oxanide' : 'antiparasitics (salicylanilide derivatives)',
'-algron' : 'alpha1 - and alpha2 - adrenoreceptor agonists',
'-trombopag' : 'thrombopoetin agonists',
'-verine' : 'spasmolytic agents (papaverine type)',
'-queside' : 'cholesterol sequestrants (glycosides)',
'-anide' : 'saluretics',
'-netide' : 'neurologic indications',
'-ase' : 'enzymes',
'-onakin' : 'interleukin-1a analogues and derivatives',
'-opilone' : 'epothilones',
'-bacept' : 'B-cells',
'-tiazem' : 'calcium channel blockers (diltiazem type)',
'-pamine' : 'dopaminergics (butopamine type)',
'-ast' : 'antiasthmatics/antiallergics (not acting primarily as antihistamines; leukotriene biosynthesis inhibitors)',
'-methasone' : 'prednisone and prednisolone derivatives',
'-nidine' : 'antihypertensives, clonidine derivatives',
'-ilide' : 'class III antiarrhythmic agents',
'-omab' : '(see -mab)',
'-clidinium' : 'muscarinic receptor agonists/antagonists (see also -ium)',
'dex-' : 'Verbal Not to Use',
'-antrone' : 'antineoplastics; anthraquinone derivatives',
'-mycin' : 'antibiotics (Streptomyces strains)',
'-toin' : 'antiepileptics (hydantoin derivatives)',
'-onium' : 'NO DEFINITION',
'-fo' : 'antihyperlipidemics (clofibrate type)',
'-fenacin' : 'muscarinic receptor antagonists',
'-locib' : 'antineoplastics that inhibit the formation of 5-LO, LTB4, LTC4, and thromboxane B2 (TxB2); and Activate PPAR nuclear receptors',
'-fensine' : 'norepinephrine, serotonin, dopamine, reuptake inhibitor',
'-octadekin' : 'interleukin type substances',
'-mk-' : 'Verbal Not to Use',
'-sporin' : 'immunosuppressants (cyclosporine type)',
'-bamate' : 'tranquilizers/antiepileptics (propanediol and pentanediol groups)',
'gado-' : 'gadolinium derivatives (principally for diagnostic use)',
'-erg' : '(see -erg-)',
'-cellose' : 'cellulose ether derivatives',
'-acetam' : '(see -racetam)',
'-por' : 'NO DEFINITION',
'-amidine' : 'NO DEFINITION',
'-tepa' : 'antineoplastics (thiotepa derivatives)',
'-previr' : 'serine protease inhibitors',
'-nicline' : 'nicotinic acetylcholine receptor partial agonists/agonists',
'-lipim' : 'lipoprotein lipase activators',
'fort-' : 'Verbal Not to Use',
'-nakin' : '(see -kin)',
'nit-' : 'NO2 - derivatives',
'-patrilat' : 'NO DEFINITION',
'-azolam' : 'diazepam derivatives',
'perfl-' : 'perfluorinated compounds used as blood substitutes and/or diagnostic agents',
'nitr-' : 'NO2 - derivatives',
'-berel' : 'beta estrogen receptor agonist',
'-fylline' : 'theophylline derivatives',
'-dd-' : 'Verbal Not to Use',
'-setron' : 'serotonin 5-HT3 antagonists',
'-cidin' : 'natural antibiotics (undefined group)',
'-protafib' : 'protein tyrosine phosphatase 1B inhibitors',
'-pertin' : 'glycine transporter/reuptake inhibitors',
'-sulind' : 'antineoplastics, sulindac metabolites',
'estr-' : 'estrogens',
'-bol' : 'anabolic steroids',
'-fovir' : 'phosphonic acid derivatives',
'-dermin' : '(see -ermin)',
'-dox' : 'antibacterials, quinazoline dioxide derivatives',
'-plase' : 'enzymes',
'-quiline' : 'antibiotics, diarylquinoline structure',
'-fetamine' : 'amfetamine derivatives',
'-orphan' : '(see -orphan)',
'-imibe-' : 'antihyperlipidaemics, acyl CoA: cholesterol acyltransferase (ACAT) inhibitors',
'-bove' : 'bovine somatotropin derivatives',
'-fermin' : '(see -ermin)',
'-plermin' : '(see -ermin)',
'-cirnon' : 'CC chemokine receptor 9 (CCR9) antagonists',
'x-' : 'Verbal Not to Use',
'-gli' : 'n/a',
'-fo-' : 'phosphoro-derivatives',
'-tioxetine' : '(see -oxetine)',
'-octakin' : '(see -kin)',
'-elestat' : 'elastase inhibitors',
'-lefacept' : 'lymphocyte function-associated antigen 3',
'-nonakin' : '(see -kin)',
'-mostat' : 'NO DEFINITION',
'-arabine' : 'antineoplastics (arabinofuranosyl derivatives) fludarabine',
'-racil' : 'uracil type antineoplastics',
'-sal' : 'anti-inflammatory agents (salicylic acid derivatives)',
'-fexor-' : 'farnesoid X receptor agonists',
'-siban' : 'oxytocin antagonists',
'cef-' : 'cephalosporins',
'-imex-' : '(see -imex)',
'-axomab' : 'see mab',
'-nonacog' : '(see -cog)',
'-closporin' : 'immunosuppressants (cyclosporine type)',
'-clidine' : 'muscarinic agonists (various indications)',
'-my-' : 'Verbal Not to Use',
'-octocog' : 'blood coagulation factor VIII',
'gly-' : 'antihyperglycemics',
'-pressin' : 'vasoconstrictors (vasopressin derivatives)',
'-codar' : 'see dar',
'-nepag' : 'Reduce conflicts with stems beginning with ne-, harmonize with INN Experts, better reflect action at EP2 receptor',
'-clone' : 'hypnotics/tranquilizers (zopclone type)',
'-stigmine' : 'cholinesterase inhibitors (physostigmine type)',
'prost-' : '(see -prost)',
'-pirdine' : 'cognition enhancers',
'-plasinin' : 'inhibitors of plasminogen activator inhibitors - type 1',
'-vos' : 'insecticides, anthelminthics, pesticides etc., phosphorus derivatives',
'-neurin' : 'neurotensin receptor antagonists; neurotropins',
'mito-' : 'antineoplastics, nucleotoxic agents',
'-sartan' : 'angiotensin II receptor antagonists',
'-oxepin' : 'tricyclic compounds',
'-imepodib' : 'inosine monophosphate dehydrogenase inhibitors',
'-lazard' : 'lipid peroxidation inhibitors',
'-alox' : 'antacids, aluminium derivatives',
'-depsin' : 'depsipeptide derivatives',
'-vastatin' : '(see -stat)',
'-k-' : 'Verbal Not to Use',
'-entan' : 'endothelin receptor antagonists',
'-adol' : 'analgesics (mixed opiate receptor agonists/antagonists)',
'-adom' : 'analgesics, tifluadom derivatives',
'gab-' : '(see -gab-)',
'-alol' : 'combined alpha and beta blockers',
'arte-' : 'antimalarials (artemisin derivatives)',
'-irudin' : 'anticoagulants (hirudin type)',
'-adox' : 'antibacterials (quinoline dioxide derivatives)',
'-dralazine' : 'antihypertensives (hydrazine-phthalazines)',
'-vir-' : 'NO DEFINITION',
'-imibe' : '(see -imibe-)',
'-gene' : 'gene therapy products',
'-mustine' : 'antineoplastics (chloroethylamine derivatives)',
'nifur-' : '5-nitrofuran derivatives',
'-mostim' : 'macrophage colony-stimulating factors (M-CSF)',
'-eptakin' : '(see -kin)',
'-orex' : 'anorexiants',
'-catib' : 'cathespin inhibitors',
'-tocin' : 'oxytocin derivatives',
'-onidine' : 'antihypertensives, clonidine derivatives',
'-cillin' : 'penicillins',
'-uramidine' : 'pentamidine derivatives/analogues',
'-enicokin' : 'interleukin-21',
'-asteride' : 'androgens / anabolic steroids',
'li-' : 'Verbal Not to Use',
'-adol-' : 'analgesics (mixed opiate receptor agonists/antagonists)',
'-melteon' : 'selective melatonin receptor agonist',
'-amostat' : 'proteolytic enzyme inhibitors',
'-ki' : 'Target: interleukin',
'-glinide' : 'antidiabetic, SGLT2 inhibitors, not phlorozin derivatives',
'-opamine' : 'dopaminergic agents dopamine derivatives used as cardiac stimulant/antihypertensives/diuretics',
'-cilpine' : 'tricyclic compounds',
'-prisnil' : 'selective progesterone receptor modulators (SPRM)',
'-teplase' : 'tissue-type plasminogen activators',
'-barb-' : 'NO DEFINITION',
'-parantag' : 'antagonists of heparin and/or low molecular weight  heparins',
'-pride' : 'sulpiride derivatives',
'-dopidine' : 'dopamine D2 receptor modulator',
'-tricin' : 'antibiotics (polyene derivatives)',
'-ae-' : 'Verbal Not to Use',
'-quistat' : 'squalene synthase inhibitors',
'-ampator' : 'modulators',
'-traposin' : 'aP2 inhibitors',
'-zolid' : 'oxazolidinone antibacterials',
'-xostat' : 'xanthine oxydase and xanthine urease inhibitor',
'-y-' : 'Verbal Not to Use',
'-tibant' : 'antiasthmatics (bradykinin antagonists)',
'-pirone' : 'anxiolytics, buspirone derivatives',
'-zolast' : 'benzoxazole derivatives',
'-glumide' : 'CCK antagonists, antiulcer, anxiolytic agent',
'-ml-' : 'Verbal Not to Use',
'-filermin' : 'leukemia-inhibiting factor',
'-tirimod' : 'napthyridine analogs',
'-mg-' : 'Verbal Not to Use',
'-ch-' : 'Verbal Not to Use',
'-gramostim' : 'granulocyte macrophage colony- stimulating factors (GM-CSF)',
'-tiapine' : 'antipsychotics (dibenzothiazepine derivatives)',
'-listat' : 'gastrointestinal lipase inhibitors',
'-dil-' : 'vasodilators (undefined group)',
'-lumab' : '(see -mab)',
'-cerfont' : 'CRF-1 (corticotropin releasing factor) receptor antagonists',
'-imod' : 'immunomodulators',
'-atadine' : 'tricyclic antiasthmatics',
'-pris' : 'steroidal compounds acting on progesterone receptors',
'-rocin' : 't-RNA synthetase inhibitors',
'ba-' : 'Verbal Not to Use',
'-kinra' : 'interleukin receptor antagonists',
'-pine' : 'tricyclic compounds',
'-pidem' : 'hypnotics/sedatives (zolpidem type)',
'-io-' : 'iodine-containing compounds other than contrast media',
'-tacept' : '(see -tacept-)',
'-gliptin' : 'dipeptidyl aminopeptidase-IV inhibitors',
'-plestim' : '(see -stim)',
'-coxib' : 'cyclooxygenase-2 inhibitors',
'-betasol' : 'prednisone and prednisolone derivatives',
'-mantadine' : 'antivirals/antiparkinsonians',
'-lubant' : 'leukotriene receptor antagonists (treatment of inflammatory skin disorders)',
'-serod' : 'serotonin receptor antagonists and partial agonists',
'-laner' : 'antiparasitics (isoxazoline compounds)',
'-poetin' : 'erythropoietins',
'-ee-' : 'Verbal Not to Use',
'-pansel' : 'P-selectin antagonists inhibiting all selectin types',
'fen-' : 'Verbal Not to Use',
'-mestane' : 'antineoplastics (aromatase inhibitors)',
'nal-' : 'narcotic agonists/antagonists',
'-zolamide' : 'carbonic anhydrase inhibitors',
'-sidone' : 'antipsychotic with binding activity on serotonin (5HT2A) and dopamine (D2) receptors',
'-traline' : 'selective serotonin reuptake inhibitors (SSRI)',
'-amidis' : 'antimyloidotics',
'-nakinra' : 'interleukin-1 (IL-1) receptor antagonists',
'-vatrep' : 'vanilloid 1 receptor antagonists',
'-ectedin' : 'ecteinascodin derivatives',
'-monam' : 'monobactam antibiotics',
'-spodar' : 'ciclosporin D derivatives',
'-isomide' : 'antiarrhythmics (disopyramide derivatives)',
'-nakalant' : 'mixed sodium/potassium channel blockers',
'-ampa-' : 'ionotropic non-NMDA (N-methyl D-aspartate) glutamate receptors',
'-quin' : 'quinoline derivatives',
'-bendan' : 'cardiac stimulants, pimobendan derivatives',
'-gest' : '(see -gest-)',
'-tant' : 'tachykinin (neurokinin) receptor antagonists',
'-mz-' : 'Verbal Not to Use',
'-tox-' : 'NO DEFINITION',
'-faxine' : 'NO DEFINITION',
'-pristin' : 'antibacterials, pristinamycin derivatives',
'-sidomine' : 'antianginals (sydnone derivatives)',
'-bol-' : 'NO DEFINITION',
'-tesind' : 'thymidilate synthetase inhibitors (benzindole derivatives)',
'-lazad' : 'lipid peroxidation inhibitors',
'-ethidine' : 'analgesics, pethidine derivatives',
'-leptine' : 'see leptin',
'-urestat' : 'urease inhibitor',
'-micin' : 'antibiotics (Micromonospora strains)',
'-cavir' : '(see -vir)',
'-axo-' : 'rat-murine hybrid antibodies',
'-virenz' : 'antivirals (non-nucleoside reverse transcriptase inhibitors; benzoxazinone derivatives)',
'-w-' : 'Verbal Not to Use',
'vin-' : 'vinca alkaloids',
'-focon' : 'hydrophobic contact lens materials',
'-poride' : 'Na/H antiport inhibitor',
'aril-' : 'antiviral (arildone derivatives)',
'-xn-' : 'Verbal Not to Use',
'-estr-' : 'NO DEFINITION',
'-prost' : 'prostaglandins',
'-cetrapib' : 'cholesterol ester transfer protein inhibitors',
'-unistat' : '(see -stat)',
'-peg-' : 'PEGylated compounds, covalent attachment of macrogol (polyethylene glycol) polymer',
'-ditan' : 'antimigraine (5-HT1 receptor agonists)',
'-olol' : 'beta-blockers (propranolol type)',
'-pin(e)' : 'tricyclic compounds',
'-arol' : 'anticoagulants (dicumarol type)',
'-tacept-' : 'T-cells',
'-pred-' : 'prednisone and prednisolone derivatives',
'-emcinal' : 'erythromycin derivatives lacking antibiotic activity',
'-ciclovir' : '(see vir-)',
'-azocine' : 'narcotic antagonists/agonists (6,7-benzomorphan derivatives)',
'-epag' : 'Reduce conflicts with stems beginning with ne-, harmonize with INN Experts, better reflect action at EP2 receptor',
'-plasmin' : 'plasmin proteins and derivatives',
'-pamil' : 'coronary vasodilators (verapamil type)',
'-sermin' : '(see -ermin)',
'-plasmid' : 'gene therapy products',
'-stinel' : '(N-methyl-D-asprate) NMDA receptor antagonist, glycine recognition site',
'fenamate' : 'fenamic acid ester or salt derivatives',
'pegol-' : 'see peg',
'-cogin' : 'blood coagulation cascade inhibitor',
'-restat' : '(see -stat)',
'-stat-' : 'enzyme inhibitors',
'-buzone' : 'anti-inflammatory analgesics, phenylbutazone derivatives',
'-osuran' : 'urotensin receptor antagonists',
'-arone' : 'antiarrhythmics',
'-lukast' : 'leukotriene receptor antagonists',
'-cocept' : '(see -cept)',
'-parin' : 'heparin derivatives and low molecular weight (or depolymerized) heparins',
'-ximab' : '(see -mab)',
'-multin' : 'mucosal tolerance inductors',
'-castat' : '(see -stat)',
'-butazone' : 'anti-inflammatory analgesics (phenylbutazone type)',
'-parib' : 'poly-ADP-ribose polymerase inhibitors',
'-glitazar' : 'PPAR agonists (not thiazolidene derivatives)',
'gest-' : '(see -gest-)',
'-calaret' : 'calcium receptor antagonists',
'-tristat' : 'tryptophan hydroxylase inhibitors',
'-calci-' : 'NO DEFINITION',
'-fos-' : '(formerly -fo-) phosphoro-derivatives',
'ar-' : 'Verbal Not to Use',
'-opran' : 'opioid receptor antagonists',
'-carbef' : 'antibiotics (carbacephem derivatives)',
'dur-' : 'Verbal Not to Use',
'-tadine' : 'loratadine derivatives',
'-mc-' : 'Verbal Not to Use',
'-les-' : 'infix for inflammatory/infectious lesions',
'-mq-' : 'Verbal Not to Use',
'-urad' : 'urate transporter e.g., urate anion exchanger 1 (URAT1) inhibitors',
'-nixin' : 'anti-inflammatory agents (anilinonicotinic acid derivatives)',
'-tapide' : 'microsomal triglyceride transfer protein (MTP) inhibitors',
'-steride' : 'testosterone reductase inhibitors',
'-grel' : 'platelet aggregation inhibitors',
'-gliflozin' : 'phlorozin derivatives, phenolic glycosides',
'-cromil' : 'antiallergics (cromoglicic acid derivatives)',
'-zotan' : '5-HT1A receptor agonists/antagonists acting primarily as neuroprotectors',
'-virsen' : 'antivirals (antisense)',
'-oxane' : 'benzodioxane derivatives',
'-panel' : 'AMPA receptor antagonists',
'-sarm' : 'selective androgen receptor modulator (non-steroidal)',
'-domide' : 'thalidomide derivatives',
'-mh-' : 'Verbal Not to Use',
'-betin' : 'Amyloid B (AB) binders',
'-cillide' : 'antibiotics, 6-aminopenicillanic acid derivatives',
'-amivir' : '(see -vir)',
'-plact' : 'platelet factor 4 analogs and derivatives',
'-erg-' : 'ergot alkaloid derivatives',
'-ivon' : 'Von Willebrand factor inhibitors',
'nico-' : 'nicotine acid or nicotinoyl alcohol derivatives',
'-metasone' : 'prednisone and prednisolone derivatives',
'-gillin' : 'antibiotics (Aspergillus strains)',
'nab-' : 'cannabinol derivatives',
'-dopa' : 'dopamine receptor agonists',
'-caftor' : 'cystic fibrosis transmembrane regulator (CFTR) protein modulators',
'-formin' : 'hypoglycemics (phenformin type)',
'ni-' : 'nicotine acid or nicotinoyl alcohol derivatives',
'-apine' : 'tricyclic compounds',
'-napanor' : 'sodium-hydrogen antiporter (also called sodium-proton exchanger) inhibitors',
'-netant' : '(see -tant)',
'-ac' : 'anti-inflammatory agents (acetic acid derivatives)',
'-farnib' : 'farnesyl transferase inhibitor',
'-rev' : 'therapeutic virus',
'-al' : 'aldehydes',
'-dodekin' : 'interleukin-12 analogues and derivatives',
'-nabant' : 'CB cannabinoid receptor antagonists',
'-prenaline' : 'bronchodilators, phenethylamine derivatives',
'-benakin' : 'interleukin-1 -B analogues and derivatives',
'-nacept' : 'interleukins',
'-dil' : 'vasodilators (undefined group)',
'-xanox' : 'antiallergic respiratory tract drugs (xanoxic acid derivatives)',
'-fibrate' : 'antihyperlipidemics (clofibrate type)',
'-pendyl' : 'vasodilators',
'-barb' : 'barbituric acid derivatives',
'-mv-' : 'Verbal Not to Use',
'-arsin' : 'organoarsenic compounds',
'-etanide' : 'diuretics (piretanide type)',
'-quantel' : '2-deoxoparaherquamide A derivatives',
'-eridine' : 'analgesics (meperidine type)',
'-basib' : 'inhibitors of the ADAM (A disintegrin and A metalloprotease) enzymes (sheddases)',
'-renone' : 'aldosterone antagonists (spironolactone type)',
'-trop-' : 'NO DEFINITION',
'iv-' : 'Not necessarily prohibitive, but definitely causes hesitation',
'-imex' : 'immunostimulants',
'vir-' : 'antivirals',
'-oxicam' : 'anti-inflammatory, isoxicam derivatives',
'-one' : 'ketones',
'cent-' : 'Verbal Not to Use',
'-siranib' : 'siRNA',
'-patril' : 'ACE (angiotensin-1 converting enzyme) and NEP (neutral endopeptidase) inhibitors',
'sal-' : 'anti-inflammatory agents (salicylic acid derivatives)',
'-tredekin' : 'interleukin type substances',
'-grastim' : '(see -stim)',
'-j-' : 'Verbal Not to Use',
'-dipine' : 'phenylpyridine vasodilators (nifedipine type)',
'-bradine' : 'bradycardic agents',
'-pril-' : 'antihypertensives (ACE inhibitors)',
'-plon' : 'non-benzodiazepine anxiolytics, sedatives, hypnotics',
'rifa-' : 'antibiotics (rifamycin derivatives)',
'-tucirev' : 'tumoricidal',
'-prazan' : 'acid pump inhibitors, not dependent on acid activation',
'bi-' : 'Verbal Not to Use',
'-exine' : 'mucolytic, bromhexine derivatives',
'-vr-' : 'Verbal Not to Use',
'-kalim' : 'potassium channel agonists',
'-oxef' : 'antibiotics (oxacefalosporanic acid derivatives)',
'-ritide' : '(see -tide)',
'-icodar' : '(see -dar)',
'-fentanil' : 'narcotic analgesics (fentanyl derivatives)',
'-actide' : 'synthetic corticotropins',
'-dar' : 'multidrug resistance inhibitors',
'-estr' : '(see estr-)',
'-xantrone' : 'antineoplastics, mitoxantrone derivatives aza-anthracenedione class of antitumor agents',
'-platin' : 'antineoplastics (platinum derivatives)',
'-lizumab' : '(see -mab)',
'-parinux' : 'antithrombotyic indirect selective synthetic factor Xa inhibitors',
'-paroid' : 'antithrombotics (heparinoid type)',
'flu-' : 'Verbal Not to Use',
'-tidine' : 'H2-receptor antagonists (cimetidine type)',
'-cic' : 'hepatoprotectives (timonacic type)',
'-yzine' : 'diphenylmethyl piperazine derivatives',
'-perone' : 'antianxiety agents/neuroleptics (4-fluoro-4-piperidinobutyrophenone',
'-quinil' : 'benzodiazepine receptor agonists, also partial or inverse (quinoline derivatives)',
'-cept' : 'receptor molecules, native or modified ( a preceding infix should designate the target)',
'-oxan' : 'alpha-adrenoceptor antagonists (benzodioxane derivatives)',
'-curium' : 'neuromuscular blocking agents (quaternary',
'-fingol' : 'sphingosine derivatives',
'-mifene' : 'antiestrogens, clomifene and tamoxifen derivatives',
'-pezil' : 'acetylcholinesterase inhibitors used in the treatment of Alzheimers disease',
'-pristone' : 'progesterone receptor antagonists',
'-frine' : 'sympathomimetic, phenethyl derivatives',
'-peridol' : 'antipsychotics (haloperidol type)',
'guan-' : 'antihypertensives (guanidine derivatives)',
'-mm-' : 'Verbal Not to Use',
'-piprant' : 'prostaglandin receptor antagonists, non prostinoid structure',
'-ampa' : 'ionotropic non-NMDA glutamate receptors',
'-orphan-' : '(see -orphan)',
'-sertib' : 'serine/threonine kinase inhibitors',
'-eptacog' : 'blood coagulation factor VII',
'-stat' : 'tryptophan hydroxylase inhibitors',
'-nertant' : 'neurotensin receptor antagonists',
'-caserin' : 'serotonin receptor agonists, primarily 5-HT2',
'-md-' : 'Verbal Not to Use',
'-espib' : 'heat shock protein inhibitors',
'-neperit' : 'neuropeptide Y5',
'-dilol' : 'vasodilators',
'-motine' : 'antivirals (quinoline derivatives)',
'-zone' : '(see -buzone)',
'-aldrate' : 'antacid aluminum salts',
'-ate' : 'cellulose derivatives',
'-meline' : 'cholinergic agonists (arecoline derivatives used in treatment of Alzheimers disease)',
'-facept' : 'lymphocyte function-associated with antigen 3 (LFA) receptor',
'-orexant' : '(see -orex)',
'-fosfamide' : 'isophosphoramide mustard derivatives',
'-trop' : '(see trop-)',
'-mesine' : 'sigma receptor ligands',
'-porfin' : 'benzoporphyrin derivatives temoporfin',
'-kalner' : 'opener of large conductance calcium-activated (maxi-k) K+ channels',
'-fenine' : 'analgesics (fenamic acid subgroup)',
'-arit' : 'antirheumatics (lobenzarit type)',
'bol-' : 'anabolic steroids',
'-andr-' : 'androgens',
'-perit' : 'neuropeptide Y receptor modulators',
'-aril' : 'antiviral (arildone derivatives)',
'-spirone' : 'anxiolytics (buspirone type) (see -dar)',
'-toran' : 'TLR4 receptor antagonists',
'-nil' : 'benzodiazepine receptor antagonists/agonists',
'-leuton' : '5-lipoxgenase inhibitors',
'-mastat' : 'matrix metalloprotease inhibitors',
'-iodarone' : 'indicates high iodine content',
'-antel' : 'anthelmintics (undefined group)',
'-manid' : 'mycolic acid inhibitors',
'-relix' : 'hormone-release inhibiting peptides',
'-tumumab' : '(see -mab)',
'-retin-' : 'retinol derivatives',
'-tide' : 'peptides',
'-morelin' : '(see -relin)',
'som-' : 'growth hormone derivatives',
'dol-' : 'From "dolar" meaning "pain" in Latin (Loose Avoid)',
'-os-' : 'bone',
'-orph-' : 'narcotic antagonists / agonists, morphinan derivates',
'-parcin' : 'glycopeptide antibiotics',
'-statin' : '(see -stat)',
'-zafone' : 'alozafone derivatives',
'-vir' : 'NO DEFINITION',
'-rubicin' : 'antineoplastic antibiotics (daunorubicin type)',
'-azepide' : 'cholecystokinin receptor antagonists',
'-gacestat' : 'gamma secretase inhibitors',
'-ni-' : 'NO2 - derivatives',
'-aj-' : 'antiarrhythmics (ajmaline derivatives)',
'-nb-' : 'Verbal Not to Use',
'-quidar' : 'quinoline derivatives',
'-spo-' : 'ciclosporin D derivatives',
'-gaptide' : 'gap junction protein channel modulators',
'-tt-' : 'Verbal Not to Use',
'-uridine' : 'antivirals; antineoplastics (uridine derivatives)',
'-cri-' : 'acridinecarboxamide derivatives',
'-sal-' : 'anti-inflammatory agents (salicylic acid derivatives)',
'es-' : 'Verbal Not to Use',
'-sporivir' : '(see -vir)',
'-fetamin(e)' : 'amfetamine derivatives',
'-arot-' : 'arotinoids',
'-decakin' : 'interleukin-10 analogues and derivatives',
'piro-' : 'Verbal Not to Use',
'retin-' : 'n/a',
'-np-' : 'Verbal Not to Use',
'-maprazole' : 'acid pump inhibitors',
'-fibric acid' : 'antihyperlipidemics (clofibrate type)',
'-gli-' : 'n/a',
'-oxin' : 'fluoroquinolone derivatives, nonantibacterial indications (e.g., antineoplastic antibiotics)',
'-capone' : 'catechol-o-methyltransferase (COMT) inhibitors',
'-grel-' : 'platelet aggregation inhibitors',
'bu-' : 'Verbal Not to Use',
'-dronic' : 'calcium metabolism regulator, pharmaceutical aid',
'-capoc' : 'agonists of the Gardos channel, or the calcium activated potassium channel of intermediate conductance',
'-tolimod' : '(see -imod)',
'-trexed' : 'antineoplastic thymidylate synthetase inhibitors',
'-peridone' : 'antipsychotics (risperidone type)',
'-cet' : 'receptors (small molecule)',
'-ribine' : 'ribofuranil derivatives (pyrazofurin type)',
'-relin' : 'prehormones or hormone-release stimulating peptides',
'-leptin' : 'leptin derivatives',
'cell-' : 'cellulose derivatives / cellulose ester derivatives for substances containinig acidic redidues',
'-zomib' : 'proteozome inhibitors',
'-penkin' : '(see -kin)',
'-filcon' : 'hydrophilic contact lens materials',
'-gestr-' : 'estrogens',
'-potide' : 'peptides with prostate cancer indications',
'-azone' : 'anti-inflammatory analgesics, phenylbutazone derivatives',
'-virdine' : '(see vir)',
'-trexate' : 'antimetabolites (folic acid derivatives)',
'-buvir' : 'RNA polymerase (NS5B) inhibitor',
'-abine' : '(see -arabine/-citabine)',
'-pin' : 'tricyclic compounds',
'-mr-' : 'Verbal Not to Use',
'-pultide' : '(see -tide)',
'-ium' : 'quaternary ammonium derivatives',
'mer-' : '(see -mer)',
'-asvir' : '(see -vir)',
'sulfa-' : 'antimicrobials (sulfonamides derivatives)',
'-gepant' : 'calcitonin gene-related peptide receptor antagonists',
'-isant' : 'histamine H3 receptor antagonists',
'-toclax' : 'BCL-2 (B-cell lymphoma 2) inhibitors',
'-ermin' : 'growth factors',
'-sopine' : 'tricyclic compounds',
'-kef-' : 'enkephalin agonists (various indications)',
'-nab-' : 'cannabinol derivatives',
'cat-' : 'Verbal Not to Use',
'-profen' : 'anti-inflammatory/analgesic agents (ibuprofen type)',
'-glurant' : 'metabotropic glutamate receptor antagonists, negative allosteric modulators',
'-tirelin' : 'thyrotropin releasing hormone analogues',
'-bufen' : 'non-steroidal anti-inflammatory agents, fenbufen derivatives',
'-troline' : 'antipsychotics (dopamine D2 antagonists)',
'-clostox' : 'botulinum toxins',
'-tirome' : 'antihyperlipidemic, thyromimetic derivatives',
'-thiouracil' : 'uracil derivatives used as thyroid antagonists',
'-limumab' : '(see -mab)',
'-nermin' : '(see -ermin)',
'-crine' : 'acridine derivatives',
'-oxifene' : 'antiestrogens, clomifene and tamoxifen derivatives',
'-dotril' : '(see -tril/trilat)',
'-prostil' : 'prostaglandins, anti-ulcer',
'-umab' : '(see -mab)',
'-uracil' : 'uracil derivatives used as thyroid antagonists and as antineoplastics',
'-mantone' : 'adamantane derivatives',
'-rixin' : 'chemokine (C-X-C motif) receptor 2 (CXCR2) modulators',
'-glitazone' : 'PPST agonists (thiazolidene derivatives)',
'iod-' : 'iodine-containing compounds other than contrast media',
'-camra' : 'antivirals (intracellular adhesion molecules, icam-1 derivatives)',
'-penem' : 'antibacterial antibiotics, carbapenem derivatives',
'-lanstat' : 'lanosterol 14a-demethylase inhibitors',
'-fungin' : 'antifungal antibiotics (undefined group)',
'-curonium' : 'NO DEFINITION',
'pris-' : 'steroidal compounds acting on progesterone receptors',
'-aril-' : 'antiviral (arildone derivatives)',
'-elvekin' : 'interleukin-11 analogues and derivatives',
'-dan' : 'positive inotropic agents (pimobendan type)',
'-octacog' : '(see -cog)',
'-criviroc' : 'CCR5 antagonists, immunomodulators',
'-astine' : 'antihistaminics (histamine-H1 receptor antagonists)',
'-conazole' : 'systemic antifungals (miconazole type)',
'-oe-' : 'Verbal Not to Use',
'dil-' : 'vasodilators (undefined group)',
'-axine' : 'antianxiety, antidepressant inhibitor of norepinephrine and dopamine re-uptake',
'-igetide' : 'peptides and glycopeptides',
'-sulam' : 'antineoplastics, apoptosis inducing sulfonamide',
'-vec' : 'gene therapy products',
'-glustat' : 'glucosyltransferase inhibitors',
'-fibatide' : '(see -tide)',
'-fetamin' : 'amfetamine derivatives',
'-exakin' : '(see -kin)',
'-gapil' : 'neuronal apoptosis inhibitors; GAPDH',
'-bermin' : 'vascular endothelial growth factors',
'-brutinib' : '(see -tinib)',
'-cort-' : 'cortisone derivatives',
'-tepine' : 'tricyclic compounds',
'-piprazole' : 'psychotropics, phenylpiperazine derivatives',
'-otilate' : 'hepatoprotectants, di-isopropyl-1,3-dithiol-malonate derivatives',
'-mw-' : 'Verbal Not to Use',
'-dutant' : '(see -tant)',
'-fentrine' : 'phosphodiesterase inhibitor',
'nic-' : 'nicotine acid or nicotinoyl alcohol derivatives',
'-th-' : 'Verbal Not to Use',
'-cyclovir' : 'antivirals (acyclovir type)',
'-crinat' : 'diuretics (ethacrynic acid derivatives)',
}
INN_AVOIDS_DICTIONARY["infix"] = ["fo", "fos", "pris", "kin", "tegr", "nal", \
"stat", "ster", "fiba", "xizu", "ph", "mf", "mv", "les", "mt", "gest", "trop", \
"imibe", "fexor", "imex", "k", "adol", "ml", "mg", "ampa", "mz", "tox", "ae", \
"axo", "xn", "peg", "my", "calci", "fos", "erg", "j", "vr", "mm", "orphan", "md", \
"mr", "os", "cri", "arot", "gli", "grel", "gestr", "y", "kef", "nab", "th", \
"cain", "gab", "mj", "toxa", "ms", "acid", "dil", "ner", "prost", "mx", "aj", \
"restat", "co", "rs", "ne", "mk", "dd", "fo", "vir", "barb", "bol", "ch", "io", \
"ee", "vin", "w", "estr", "tacept", "pred", "mc", "mq", "mh", "h", "aril", "pril", \
"andr", "retin", "orph", "ni", "nb", "spo", "tt", "sal", "np", "mw", "oe", "cort", ]

INN_AVOIDS_DICTIONARY["prefix"] = ["calci", "perflu", "al", "erg", "me", "nico", \
"pred", "cort", "barb", "str", "nitro", "peg", "dex", "fort", "nit", "perfl", \
"estr", "gly", "prost", "gab", "arte", "nifur", "li", "bi", "ba", "cef", "vin", \
"aril", "pegol", "nab", "ni", "cent", "rifa", "flu", "guan", "bol", "som", "fo", \
"piro", "retin", "gest", "sulfa", "dil", "nic", "imex", "di", "rac", "deci", "z", \
"efex", "cel", "mer", "ca", "lev", "trop", "fen", "gado", "nitr", "ben", "x", \
"mito", "sal", "nal", "ar", "io", "iv", "vir", "dol", "es", "gli", "bu", "cell", \
"cat", "iod", "dur", "pris"]

INN_AVOIDS_DICTIONARY["suffix"] = ["abine", "ac", "acetam", "actide", "adol", \
"adom", "adox", "afenone", "afil", "al", "aldrate", "algron", "alol", "alox", \
"amidine", "amidis", "amivir", "amostat", "ampa", "ampanel", "ampator", "anib", \
"anide", "anserin", "antel", "antrone", "apine", "apsel", "arabine", "aril", \
"arit", "arol", "arone", "arotene", "arsin", "ase", "ast", "asteride", "astine", \
"asvir", "atadine", "ate", "axine", "axomab", "azam", "azenil", "azepam", \
"azepide", "azocine", "azolam", "azoline", "azone", "azosin", "bacept", "bactam", \
"bamate", "barb", "basib", "begron", "benakin", "bendan", "bendazole", "bercept", \
"berel", "bermin", "bersat", "betasol", "betin", "bol", "bove", "bradine", "brate", \
"brutinib", "bufen", "bulin", "butan", "butazone", "buvir", "buzone", "caftor", \
"caine", "calaret", "calcet", "caleret", "camra", "camsule", "capoc", "capone", \
"carbef", "carnil", "casan", "caserin", "castat", "catib", "cavir", "cellose", \
"cept", "cerfont", "cet", "cetrapib", "cic", "ciclib", "ciclovir", "cidin", \
"ciguat", "cillide", "cillin", "cillinam", "cilpine", "cirnon", "cisteine", \
"citabine", "citinib", "cizumab", "clidine", "clidinium", "clomol", "clone", \
"closporin", "clostox", "cocept", "codar", "cog", "cogin", "conazole", "corat", \
"cort", "coxib", "cridar", "crinat", "crine", "criviroc", "cromil", "curium", \
"curonium", "cycline", "cyclovir", "dan", "dapsone", "dar", "decakin", "degib", \
"denant", "denoson", "depsin", "dermin", "dil", "dilol", "dipine", "dismase", \
"distim", "ditan", "ditraz", "dodekin", "domide", "dopa", "dopidine", "dore", \
"dotin", "dotril", "dox", "dralazine", "drimer", "drine", "dronate", "dronic", \
"dutant", "dyl", "ectedin", "ectin", "elestat", "elvakin", "elvekin", "emcinal", \
"enicokin", "entan", "epag", "eptacog", "eptakin", "erg", "eridine", "ermin", \
"espib", "estr", "estrant", "etanide", "ethidine", "exakin", "exine", "facept", \
"farcept", "farin", "farnib", "faxine", "fenacin", "fenamic", "fenin", "fenine", \
"fensine", "fentanil", "fentrine", "fermin", "fetamin", "fetamin(e)", "fetamine", \
"fexorate", "fiban", "fibatide", "fibrate", "fibric acid", "filcon", "filermin", \
"fingol", "flapon", "flurane", "fo", "focon", "folastat", "formin", "fosfamide", \
"fovir", "fradil", "frine", "fulven", "fungin", "fylline", "gab", "gacestat", \
"ganan", "gapil", "gaptide", "gatran", "gene", "gepant", "gest", "giline", "gillin", \
"gli", "gliatin", "gliflozin", "glinide", "gliptin", "glitazar", "glitazone", \
"glumide", "glurant", "glustat", "glutide", "golide", "golix", "gosivir", \
"gramostim", "grastim", "grel", "ibat", "ibine", "icam", "icodar", "ifen", "ifene", \
"igetide", "ilide", "imepodib", "imex", "imibe", "imidar", "imod", "imus", "ine", \
"inostat", "iodarone", "iphene", "irudin", "isant", "isomide", "ium", "iv", "ivon", \
"ixafor", "izine", "kacin", "kalant", "kalim", "kalner", "ki", "kin", "kinra", "kiren", \
"laner", "lanstat", "lazad", "lazard", "lefacept", "leptin", "leptine", "leukin", "leuton", \
"limumab", "lind", "lintide", "lipim", "lisib", "listat", "lizumab", "locib", "lubant", \
"lukast", "lumab", "luren", "lutamide", "lutril", "mab", "manid", "mantadine", "mantine", \
"mantone", "mapimod", "maprazole", "mastat", "meline", "melteon", "mer", "mesine", "mestane", \
"metacin", "metasone", "methasone", "micin", "mifene", "milast", "monam", "morelin", "moren", \
"mostat", "mostim", "motine", "moxin", "mulin", "multin", "murtide", "mustine", "mycin", "nab", \
"nabant", "nacept", "nakalant", "nakin", "nakinra", "napanor", "napant", "naritide", "navir", \
"nepag", "neperit", "nercept", "nermin", "nertant", "nesib", "netant", "netide", "neurin", \
"nicate", "nicline", "nidap", "nidazole", "nidine", "nil", "nixin", "nonacog", "nonakin", \
"octacog", "octadekin", "octakin", "octocog", "ol", "olol", "olone", "omab", "onakin", "one", \
"onide", "onidine", "onium", "opamine", "opilone", "opran", "orex", "orexant", "orphan", \
"osuran", "otermin", "otilate", "ox", "oxacin", "oxan", "oxane", "oxanide", "oxef", "oxepin", \
"oxetine", "oxicam", "oxifene", "oxin", "oxopine", "pab", "pafant", "pamide", "pamil", "pamine", \
"panel", "pansel", "parantag", "paratide", "parcil", "parcin", "parib", "parin", "parinux", \
"paroid", "patril", "patrilat", "paxar", "pendyl", "penem", "penkin", "peridol", "peridone", \
"perit", "perone", "pertin", "pezil", "pidem", "pin", "pin(e)", "pine", "piprant", "piprazole", \
"pirdine", "pirone", "pirox", "pitant", "plact", "pladib", "planin", "plase", "plasinin", "plasmid", \
"plasmin", "platin", "plermin", "plestim", "plon", "poetin", "por", "porfin", "poride", "potide", \
"pramine", "prazan", "prazole", "pred", "prenaline", "pressin", "previr", "pride", "pril", "prilat", \
"prim", "prinim", "pris", "prisnil", "pristin", "pristone", "profen", "proget", "prost", "prostil", \
"protafib", "pultide", "punil", "quantel", "queside", "quidar", "quiline", "quin", "quine", "quinil", \
"quistat", "racetam", "racil", "rafenib", "relin", "relix", "renone", "restat", "retin", "rev", "rian", \
"ribine", "rinone", "ritide", "rixin", "rizine", "rocin", "rolimus", "rozole", "rsen", "rubicin", "sal", \
"sarm", "sartan", "semide", "sermin", "serod", "serpine", "sertib", "setrag", "setron", "siban", \
"sidomine", "sidone", "siranib", "sonan", "sopine", "spirone", "spodar", "sporin", "sporivir", \
"stat", "statin", "steine", "steride", "stigmine", "stim", "stinel", "sulam", "sulfan", "sulind", \
"tacept", "tadine", "tansine", "tant", "tapide", "taxel", "tecan", "tecarin", "tegrast", "tegravir", \
"telstat", "tepa", "tepine", "teplase", "tercept", "termin", "terol", "terone", "tesind", "texafin", \
"thiazide", "thiouracil", "tiapine", "tiazem", "tibant", "tide", "tidine", "tilide", "tiline", "tinib", \
"tiostat", "tioxetine", "tirelin", "tirimod", "tirome", "tizide", "tocin", "toclax", "toin", "tolimod", \
"toran", "trakin", "trakinra", "traline", "traposin", "tredekin", "trexate", "trexed", "tricin", "tril", \
"trilat", "triptan", "triptyline", "tristat", "troban", "trodast", "troline", "trombopag", "trop", \
"tucirev", "tumumab", "uclin", "umab", "unistat", "uplase", "uracil", "urad", "uramidine", "urestat", \
"uridine", "vaptan", "vastatin", "vatrep", "vec", "verine", "vir", "vircept", "virdine", "virenz", \
"virimat", "virine", "viroc", "virsen", "vos", "vudine", "xaban", "xanox", "xantrone", "ximab", "xostat", \
"yzine", "zafone", "zepine", "zolamide", "zolast", "zolid", "zomib", "zone", "zotan", "zotide", "zumab"]
